### ISSUE TITLE
Docker Community tutorials link is broken

### ISSUE THREAD

**Issue by vegasbrianc** [docker/labs#121]
I noticed the Docker Community link is broken. I'm not sure where these tutorials or should live or I would have fixed it already.

**Comment by ManoMarks** [comment]
Hmmmm is gone, @vcoisne do you know what happened?
https://github.com/docker/community/blob/master/tutorials/docker-tutorials.md

**Comment by bargemb** [comment]
@vcoisne Can I take this issue ? I'm new to docker contributions and this will help me to understand the process better.

**Comment by vcoisne** [comment]
@ManoMarks we deleted it to focus on https://github.com/docker/community/tree/master/Docker-Meetup-Content 

@bargemb that would be awesome. Please feel free to submit a PR with the link I included above :)
thanks for your contribution

**Comment by bargemb** [comment]
@vcoisne created pull request #127 for the same

**Comment by ManoMarks** [comment]
Fixed in #127
