### ISSUE TITLE
Change description in votingapp.md for "Build and tag images" section

### ISSUE THREAD

**Issue by bargemb** [docker/labs#125]
`docker build` command given in this section explicitly mentions `path` for the apps. 
For example 
> docker build --no-cache -t <YOUR_DOCKER_ID>/votingapp_voting-app vote

`vote` in this case.

However descriptions says 

> Navigate to each of the directories where you have a Dockerfile to build and tag your images that you want to submit.

This results in following error

> unable to prepare context: unable to evaluate symlinks in context path: lstat /root/example-voting-app/vote/vote: no such file or directory

**Comment by bargemb** [comment]
Pull request #129 created for this issue.

**Comment by ManoMarks** [comment]
Fixed in #129
