### ISSUE TITLE
Expand SQL Server lab with scenario that includes distributed transactions

### ISSUE THREAD

**Issue by dimitarivanov** [docker/labs#128]
I'm struggling for some time to make distributed transactions work with SQL Server in a container. An example lab that accomplishes this will be quite beneficial.

Here is more information on the issue that I'm facing: [Service running inside of a container cannot participate in distributed transaction](https://github.com/Microsoft/Virtualization-Documentation/issues/494)

**Comment by dimitarivanov** [comment]
Based on the response in the opened issue this use case is not supported so I'm closing this enhancement.

Thanks!

**Comment by tstrypko** [comment]
Do you have more info on why exactly MSDTC is not supported? Some services are missing?

(Please see my investigation: https://github.com/Microsoft/Virtualization-Documentation/issues/494#issuecomment-288652149)
