### ISSUE TITLE
client version 1.22 is too old. Minimum supported API version is 1.24, please upgrade your client to a newer version

### ISSUE THREAD

**Issue by ferpega** [docker/labs#135]
When I try to follow the README.md in this:
https://github.com/docker/labs/blob/master/windows/windows-containers/MultiContainerApp.md

I get this message:

`$ docker-compose -f ./docker-compose.windows.yml up`

> client version 1.22 is too old. Minimum supported API version is 1.24, please upgrade your client to a newer version

This is my docker-compose version information:

`$ docker-compose version`

> docker-compose version 1.9.0, build 2585387
> docker-py version: 1.10.6
> CPython version: 2.7.12
> OpenSSL version: OpenSSL 1.0.2h  3 May 2016

It is running on windows-container mode.

If I try to switch to linux-container mode this my 'build' result:
`$ docker-compose -f ./docker-compose.windows.yml build`

> db uses an image, skipping
> Building web
> Step 1/13 : FROM microsoft/dotnet:1.0.0-preview2-windowsservercore-sdk
> 1.0.0-preview2-windowsservercore-sdk: Pulling from microsoft/dotnet
> Service 'web' failed to build: unknown blob

It is very annoying start with a simple tutorial and get this kind of problems.  👎  :-(

Any help would be welcome.

**Comment by ferpega** [comment]
Changing this file:

> docker-compose.windows.yml

Setting its version from '2' to '2.1' and executing 'build' again, It does not throw the error, but after a lot of time it seems not doing anything and stuck on this:

`$ docker-compose -f ./docker-compose.windows.yml build`

> db uses an image, skipping
> Building web
> Step 1/13 : FROM microsoft/dotnet:1.0.0-preview2-windowsservercore-sdk
> 1.0.0-preview2-windowsservercore-sdk: Pulling from microsoft/dotnet

**Comment by ManoMarks** [comment]
@ferpega please file an issue on the Compose repo https://github.com/docker/compose
