### ISSUE TITLE
I get unknown blob

### ISSUE THREAD

**Issue by briviere** [docker/labs#142]
I'm trying to go through the lab but I keep getting the following:

>docker pull microsoft/windowsservercore:10.0.14393.321
10.0.14393.321: Pulling from microsoft/windowsservercore
9c7f9c7d9bc2: Retrying in 1 second
de5064718b3f: Downloading
unknown blob

**Comment by ManoMarks** [comment]
@briviere Are you using [Docker for Windows](https://docs.docker.com/docker-for-windows/)? If so, have you made sure that you're in [Windows Container](https://docs.docker.com/docker-for-windows/#/switch-between-windows-and-linux-containers-beta-feature) mode

**Comment by briviere** [comment]
Hello

Yes Docker for Windows.  No I'm not in windows container mode.  I don't see
anything that shows me how to switch to Windows Container Mode?

**Comment by ManoMarks** [comment]
[This page](https://github.com/docker/labs/blob/master/windows/windows-containers/Setup-Win10.md) has an animated gif showing you how to switch to Windows Container Mode.
