### ISSUE TITLE
Unable to create dacpac file

### ISSUE THREAD

**Issue by wmeng19** [docker/labs#146]
Hi Admin,

I follow the guide step by step by unable to create the the dacpac file in window server 2016. It got no error . After the "docker build -t assets-db-builder -f Dockerfile.builder ." there are not Assets.Database.dacpac been generated. Please help.

Eng,

**Comment by sixeyed** [comment]
@wmeng19 that command just builds the Docker image which can create a Dacpac. You then need to run the image - this is the last step in

**Comment by ManoMarks** [comment]
can we close this issue?

**Comment by ManoMarks** [comment]
Closing for lack of follow-up, we can reopen of necessary

**Comment by wmeng19** [comment]
Hi @sixeyed & @ManoMarks sorry for the latest response because i been assign to other task. Yes i understand "docker run --rm -v $pwd\out:c:\bin -v $pwd\src:c:\src assets-db-builder" is the last command to generate the dacpac file. It no problems to create the image but while I execute command docker run --rm -v $pwd\out:c:\bin -v $pwd\src:c:\src assets-db-builder it give me error to mapping as below:

> C:\Program Files\Docker\docker.exe: Error response from daemon: invalid bind mount spec "C:\\scr\\src:c:\\src": invalid volume specification: 'C:\scr\src:c:\src': invalid mount config for type
>  "bind": bind source path does not exist.


I don't see any volume set for C:\bin & C:\scr....Is that causing the error. I read other docker document/example they all apply command Volume in ther docker file so that when create container that can map it. Another item make me confuse is we didn't copy those Assets.Database into image...is that correct? Below is the exact docker file as in this example:

```
# escape=`
FROM microsoft/windowsservercore
MAINTAINER Elton Stoneman <elton@docker.com>

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop';"]

RUN Install-PackageProvider -Name chocolatey -Force; `
    Install-Package -Name microsoft-build-tools -RequiredVersion 14.0.25420.1 -Force; `
    Install-Package dotnet4.6-targetpack -Force

RUN Install-Package nuget.commandline -Force; `
    & C:\Chocolatey\bin\nuget install Microsoft.Data.Tools.Msbuild
CMD cd 'C:\Program Files (x86)\MSBuild\14.0\Bin'; `
    .\msbuild C:\src\Assets.Database\Assets.Database.sqlproj `
    /p:SQLDBExtensionsRefPath="C:\Microsoft.Data.Tools.Msbuild.10.0.61026\lib\net40" `
    /p:SqlServerRedistPath="C:\Microsoft.Data.Tools.Msbuild.10.0.61026\lib\net40"; `
    cp 'C:\src\Assets.Database\bin\Debug\Assets.Database.dacpac' 'c:\bin'
```

**Comment by ferventcoder** [comment]
@wmeng19 don't use the Chocolatey prototype provider that is in OneGet/PackageManagement - prefer instead to use Chocolatey (choco.exe) directly. At least until there is an official provider available.
