### ISSUE TITLE
Build Error: flask-app

### ISSUE THREAD

**Issue by uttyleric** [docker/labs#147]
I ran `docker build` and received the following error. Any idea what I need to adjust to resolve it?

Step 2 : RUN apk add --update py-pip
 ---> Running in 1ff1442df618
fetch http://dl-cdn.alpinelinux.org/alpine/v3.5/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.5/community/x86_64/APKINDEX.tar.gz
ERROR: unsatisfiable constraints:
  py-pip (virtual):
    provided by: py2-pip
    required by: world[py-pip]
The command '/bin/sh -c apk add --update py-pip' returned a non-zero code: 1

**Comment by ManoMarks** [comment]
I'm unable to reproduce this issue. A couple of thoughts:
1) It was a temporary problem with the alpine linux cdn, try building again and see if you get the same problem.
2) There's a network issue on your end blocking access to the alpine linux cdn. Could be a problem if you are running through a proxy server. Try running it on another network.

**Comment by ManoMarks** [comment]
Another idea, try changing the first line to:
`FROM alpine:3.4`
which specifies a specific version of the alpine base image to use.

**Comment by vishaldodiya** [comment]
On aplinelinux forum says that py-pip is for 3.5 also as mentioned by @ManoMarks  version so try changing py-pip to py2-pip.

**Comment by frjaraur** [comment]
When using flask for development of my apps I  always use python images for base image. For example, in my latest project I am using FROM python:3.5-alpine which uses alpine 3.5 as base OS.

**Comment by anselal** [comment]
@vishaldodiya Changing py-pip to py2-pip worked for me !!!
