### ISSUE TITLE
How to get docker inside docker working

### ISSUE THREAD

**Issue by sylar9232** [docker/labs#162]
Hello,

i have a question if i can install docker inside docker. I have tried, but all i get is this error:
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.25/containers/json: open //./pipe/docker_engine: The system cannot find the file specified.

here is my Dockerfile:
```

FROM windows-java:jre1.8.0_91
EXPOSE 3500 3500

SHELL ["powershell"]
ARG BASE_URL
ARG SECRET

ADD script.ps1 C:/
RUN md ~/.ssh
ADD config C:/
ADD id_rsa C:/
ADD config C:/Users/ContainerAdministrator/.ssh
ADD id_rsa C:/Users/ContainerAdministrator/.ssh

RUN Set-Item -path env:PATH -value ($env:PATH + ';C:\Program Files\Docker')
RUN Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force
RUN Install-WindowsFeature hyper-v
RUN Install-Module -Name DockerMsftProvider -Repository PSGallery -Force
RUN Install-Package -Name docker -ProviderName DockerMsftProvider -Force

RUN (New-Object System.Net.WebClient).DownloadFile('{0}/jnlpJars/slave.jar' -f $env:BASE_URL, 'slave.jar') ;

ENTRYPOINT ["C:\Java\jre1.8.0_91\bin\java.exe", "-jar", ".\slave.jar"]

```
What I'm trying to do is to have this image connected to jenkins and then would jenkis restart inside images (so docker inside docker) after change in git.

Thanks!

**Comment by ManoMarks** [comment]
Hi! Please join the [Docker community](http://dockr.ly/MeetUp) for this kind of support, you'll receive an invite to the slack community, and if you have a bug please file it at https://github.com/docker/docker
