### ISSUE TITLE
Possible "Docker Swarm" misspell in slides

### ISSUE THREAD

**Issue by ettore26** [docker/labs#168]
Hi! 

Possible misspell in [labs/slides/docker-introduction.pdf](https://github.com/docker/labs/blob/master/slides/docker-introduction.pdf) file, slide n.54 line 3, which says:

- "Filters: Used by **Docker Swam** scheduler to create and run container"

Possible correction: 

- "Filters: Used by **Docker Swarm** scheduler to create and run container"

**Comment by ManoMarks** [comment]
@arun-gupta ^^^

**Comment by ManoMarks** [comment]
Fixed, thanks for the report
