### ISSUE TITLE
the error please help me

### ISSUE THREAD

**Issue by dockerwang** [docker/labs#177]
** PLEASE ONLY USE THIS ISSUE TRACKER TO SUBMIT ISSUES WITH THE DOCKER LABS TUTORIAL CONTENT **

* If you have a bug working with Docker itself, not related to these labs, please file the bug on the [Docker repo](https://github.com/docker/docker) *
* If you would like general support figuring out how to do something with Docker, please use the Docker Slack channel. If you're not on that channel, sign up for the [Docker Community](http://dockr.ly/MeetUp) and you'll get an invite. *
* Or go to the [Docker Forums](https://forums.docker.com/) *

Please provide the following information so we can assess the issue you're having

**Which lab is it that you're having issues with?**

**Description**

i just do this step by step your examles, but I do not execute the later step(the error blow) 

**Steps to reproduce the issue, if relevant:**
1. the error tips my pip version too low but i do not how to update because could not find where is the pip
2. By the ‘ find -name ' to find pip ,the tty show docker layeres
3.  thank you your help!

**Describe the results you received:

Sending build context to Docker daemon 576.5 kB
Step 1/8 : FROM alpine
 ---> 88e169ea8f46
Step 2/8 : RUN apk add --update py-pip
 ---> Using cache
 ---> 45a9fdd3bdab
Step 3/8 : COPY requirements.txt /usr/src/app/
 ---> Using cache
 ---> 4ff5d7d97da7
Step 4/8 : RUN pip install --no-cache-dir -r /usr/src/app/requirements.txt
 ---> Running in cabc45637cac
Collecting sk==0.10.1 (from -r /usr/src/app/requirements.txt (line 1))
  Could not find a version that satisfies the requirement sk==0.10.1 (from -r /usr/src/app/requirements.txt (line 1)) (from versions: )
No matching distribution found for sk==0.10.1 (from -r /usr/src/app/requirements.txt (line 1))
You are using pip version 9.0.0, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
The command '/bin/sh -c pip install --no-cache-dir -r /usr/src/app/requirements.txt' returned a non-zero code: 1

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:38:28 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:38:28 2017
 OS/Arch:      linux/amd64
 Experimental: false

**Output of `docker info`:**

Containers: 11
 Running: 0
 Paused: 0
 Stopped: 11
Images: 13
Server Version: 1.13.1
Storage Driver: overlay
 Backing Filesystem: xfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: jhrfakm8cz17c6bctdd1bwio2
 Is Manager: true
 ClusterID: u30ino1hki9ydjontp7r41fqe
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 192.168.100.128
 Manager Addresses:
  192.168.100.128:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1
runc version: 9df8b306d01f59d3a8029be411de015b7304dd8f
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-514.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 976.5 MiB
Name: localhost.localdomain
ID: LCLE:7CAF:RVBO:4D6T:D2TV:BXDN:QGAF:Z5AD:BNDU:DO2K:R53B:46XF
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Registry Mirrors:
 http://5445e28f.m.daocloud.io/
Live Restore Enabled: false

**Additional environment details (AWS, Docker for Mac, Docker for Windows, VirtualBox, physical, etc.):**

**Comment by ManoMarks** [comment]
Could you please give more details? Could you describe the steps you went through and the exact error messages you got? Also the output of `docker version`  and `docker info`.

Thanks

**Comment by dockerwang** [comment]
thinks mano, I have edited my requstion. please help me to resolve the problem thanks

**Comment by StefanScherer** [comment]
@dockerwang 
Check your `requirements.txt` file. The output above shows `sk==0.10.1`, but the [tutorial](https://github.com/docker/labs/blob/da78d804f3df3c9095150a71db3b2b4bd696681e/beginner/chapters/webapps.md#requirementstxt) shows `Flask==0.10.1`.
Maybe a problem using VIM and pasting code without being in insert mode? ;-)

**Comment by dockerwang** [comment]
Thinks! it works! But it still tips 
.....
Successfully installed Flask-0.10.1 Jinja2-2.9.5 MarkupSafe-0.23 Werkzeug-0.11.15 itsdangerous-0.24
You are using pip version 9.0.0, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
 ---> 7b5f4c778418
Removing intermediate container 39a9a93a2c0b
......
can you give me some  abort the pip update of suggest? 
Once again offer my sincere thanks

**Comment by StefanScherer** [comment]
@dockerwang Well, this is only a suggestion. Alpine installs py2-pip (9.0.0-r1) which should be good enough for the tutorial. Otherwise try the suggested command with an extra RUN instruction before running pip with the requirements.txt file.

**Comment by dockerwang** [comment]
ok ,I know thanks!

**Comment by ManoMarks** [comment]
Thanks @stefanscherer
