### ISSUE TITLE
Usage for Mac OSX

### ISSUE THREAD

**Issue by scheung38** [docker/labs#185]
Is this for running inside a Mac OSX?

**Comment by ManoMarks** [comment]
@scheung38 What lab are you referring to? If you are looking for more info on Docker for Mac, check out this page: https://docs.docker.com/docker-for-mac/

**Comment by scheung38** [comment]
HI Mano,

I am looking to run Win apps in Windows container, on top of my Mac...is that possible? As I want to run inside Docker as opposed to Vagrant box

**Comment by ManoMarks** [comment]
No, Windows containers only work on Windows at this point.

**Comment by scheung38** [comment]
But I thought that is the point of container technology, the host and VM can be any independent OS to provide flexibility for both OS, so at the moment this is only true for Vagrant or Parallels?

**Comment by ManoMarks** [comment]
Yes, that is the point. However, Microsoft restricts the use of Windows containers to the Windows platform at this time. You can run linux containers on mac, windows, or other linux distros, but not Windows containers.

**Comment by ManoMarks** [comment]
If you want more info on Docker, you can ask over on the forums. This issue tracker is for the tutorials: https://forums.docker.com/
