### ISSUE TITLE
No overload for method 'UseInMemoryDatabase' takes 0 arguments

### ISSUE THREAD

**Issue by jcemoller** [docker/labs#187]
**Which lab is it that you're having issues with?**

https://github.com/docker/labs/blob/master/windows/windows-containers/MultiContainerApp.md

**Description**

A clean install of Windows Server 2016 in Azure, following the steps in the quickstart to add git and docker, then following lab notes to install Musicstore. Breaks on step 12/16, building the application, with error "No overload for method 'UseInMemoryDatabase' takes 0 arguments".

**Describe the results you received:**

Step 12/16 : RUN dotnet build --framework netcoreapp1.1 .\samples\MusicStore
 ---> Running in 059da701583a
Microsoft (R) Build Engine version 15.1.545.13942
Copyright (C) Microsoft Corporation. All rights reserved.

C:\Users\ContainerAdministrator\.nuget\packages\internal.aspnetcore.sdk\1.0.1-rc2-15191\build\Git.targets(15,5): warning
 : Unable to determine active git branch. [C:\MusicStore\samples\MusicStore\MusicStore.csproj]
C:\Users\ContainerAdministrator\.nuget\packages\internal.aspnetcore.sdk\1.0.1-rc2-15191\build\Git.targets(32,5): warning
 : Property 'CommitHash' was not set [C:\MusicStore\samples\MusicStore\MusicStore.csproj]
StartupOpenIdConnect.cs(60,37): error CS1501: No overload for method 'UseInMemoryDatabase' takes 0 arguments [C:\MusicSt
ore\samples\MusicStore\MusicStore.csproj]
Startup.cs(42,29): error CS1501: No overload for method 'UseInMemoryDatabase' takes 0 arguments [C:\MusicStore\samples\M
usicStore\MusicStore.csproj]
ForTesting\Mocks\MicrosoftAccount\TestMicrosoftAccountEvents.cs(21,54): error CS0103: The name 'MicrosoftAccountHelper'
does not exist in the current context [C:\MusicStore\samples\MusicStore\MusicStore.csproj]
ForTesting\Mocks\MicrosoftAccount\TestMicrosoftAccountEvents.cs(22,54): error CS0103: The name 'MicrosoftAccountHelper'
does not exist in the current context [C:\MusicStore\samples\MusicStore\MusicStore.csproj]
ForTesting\Mocks\MicrosoftAccount\TestMicrosoftAccountEvents.cs(23,54): error CS0103: The name 'MicrosoftAccountHelper'
does not exist in the current context [C:\MusicStore\samples\MusicStore\MusicStore.csproj]
ForTesting\Mocks\MicrosoftAccount\TestMicrosoftAccountEvents.cs(24,54): error CS0103: The name 'MicrosoftAccountHelper'
does not exist in the current context [C:\MusicStore\samples\MusicStore\MusicStore.csproj]
ForTesting\Mocks\MicrosoftAccount\TestMicrosoftAccountEvents.cs(27,54): error CS0103: The name 'MicrosoftAccountHelper'
does not exist in the current context [C:\MusicStore\samples\MusicStore\MusicStore.csproj]
ForTesting\Mocks\Google\TestGoogleEvents.cs(22,67): error CS0117: 'GoogleHelper' does not contain a definition for 'GetI
d' [C:\MusicStore\samples\MusicStore\MusicStore.csproj]
ForTesting\Mocks\Google\TestGoogleEvents.cs(23,67): error CS0117: 'GoogleHelper' does not contain a definition for 'GetF
amilyName' [C:\MusicStore\samples\MusicStore\MusicStore.csproj]
ForTesting\Mocks\Google\TestGoogleEvents.cs(24,67): error CS0117: 'GoogleHelper' does not contain a definition for 'GetN
ame' [C:\MusicStore\samples\MusicStore\MusicStore.csproj]
ForTesting\Mocks\Facebook\TestFacebookEvents.cs(20,54): error CS0103: The name 'FacebookHelper' does not exist in the cu
rrent context [C:\MusicStore\samples\MusicStore\MusicStore.csproj]
ForTesting\Mocks\Facebook\TestFacebookEvents.cs(21,54): error CS0103: The name 'FacebookHelper' does not exist in the cu
rrent context [C:\MusicStore\samples\MusicStore\MusicStore.csproj]
ForTesting\Mocks\Facebook\TestFacebookEvents.cs(22,54): error CS0103: The name 'FacebookHelper' does not exist in the cu
rrent context [C:\MusicStore\samples\MusicStore\MusicStore.csproj]
ForTesting\Mocks\Facebook\TestFacebookEvents.cs(23,54): error CS0103: The name 'FacebookHelper' does not exist in the cu
rrent context [C:\MusicStore\samples\MusicStore\MusicStore.csproj]
ForTesting\Mocks\Facebook\TestFacebookEvents.cs(24,99): error CS0103: The name 'FacebookHelper' does not exist in the cu
rrent context [C:\MusicStore\samples\MusicStore\MusicStore.csproj]
ForTesting\Mocks\StartupOpenIdConnectTesting.cs(48,37): error CS1501: No overload for method 'UseInMemoryDatabase' takes
 0 arguments [C:\MusicStore\samples\MusicStore\MusicStore.csproj]
ForTesting\Mocks\StartupSocialTesting.cs(53,37): error CS1501: No overload for method 'UseInMemoryDatabase' takes 0 argu
ments [C:\MusicStore\samples\MusicStore\MusicStore.csproj]

Build FAILED.

**Describe the results you expected:**

A successful build.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      17.03.0-ee-1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   9094a76
 Built:        Wed Mar  1 00:49:51 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.03.0-ee-1
 API version:  1.26 (minimum version 1.24)
 Go version:   go1.7.5
 Git commit:   9094a76
 Built:        Wed Mar  1 00:49:51 2017
 OS/Arch:      windows/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 2
 Running: 0
 Paused: 0
 Stopped: 2
Images: 12
Server Version: 17.03.0-ee-1
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: l2bridge l2tunnel nat null overlay transparent
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 14393 (14393.729.amd64fre.rs1_release_inmarket_rim.170123-1753)
Operating System: Windows Server 2016 Datacenter
OSType: windows
Architecture: x86_64
CPUs: 2
Total Memory: 7 GiB
Name: Win2016Test
ID: A3SA:5LM6:VKW5:CO3X:X2CU:QGPE:VPY7:R4VL:QDLN:AA6K:IAK7:4W4H
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, Docker for Mac, Docker for Windows, VirtualBox, physical, etc.):**

**Comment by ManoMarks** [comment]
@sixeyed can you take a look?
