### ISSUE TITLE
hello-dotnetbot is not for Windows

### ISSUE THREAD

**Issue by martinmosegaard** [docker/labs#189]
**Which lab is it that you're having issues with?**

https://github.com/docker/labs/tree/master/windows/hello-dotnetbot

**Description**

This tutorial is in the Windows category, so I expected it would run on Windows.
But it does not work on Windows, so it should have more details in the README.

**Steps to reproduce the issue, if relevant:**
1. `docker build -t dotnetbot .`

**Describe the results you received:**

```
PS C:\projects\labs\windows\hello-dotnetbot> docker build -t dotnetbot .
Sending build context to Docker daemon 8.192 kB
Step 1/7 : FROM microsoft/dotnet:latest
latest: Pulling from microsoft/dotnet
image operating system "linux" cannot be used on this platform
```

**Describe the results you expected:**

I expected stuff in the `windows` folder to run on Windows. I think this should be moved or at least the README should be better.

**Additional environment details (AWS, Docker for Mac, Docker for Windows, VirtualBox, physical, etc.):**

Windows Server 2016 in VirtualBox.

**Comment by ManoMarks** [comment]
@sixeyed @spara please determine if we should be preserving this lab and if so where to put it

**Comment by spara** [comment]
I think we should remove it.
