### ISSUE TITLE
'helloworld' directory does not exist

### ISSUE THREAD

**Issue by johanjanssen** [docker/labs#207]
On https://github.com/docker/labs/blob/master/developer-tools/java/chapters/ch03-build-image.adoc the instructions use the 'helloworld' directory, see below. However that directory does not exist in the cloned repo. Simply removing the 'helloworld' directory from the mvn commands solved it.

Clone the sample code from https://github.com/arun-gupta/docker-java-sample/.
Create the Docker image:

mvn -f docker-java-sample/helloworld/pom.xml package -Pdocker

.....

Run the Docker container:

mvn -f docker-java-sample/helloworld/pom.xml install -Pdocker

**Comment by ManoMarks** [comment]
@arun-gupta can you take a look?

**Comment by arun-gupta** [comment]
Sent a PR: https://github.com/docker/labs/pull/209
