### ISSUE TITLE
Build command is not mentioned

### ISSUE THREAD

**Issue by johanjanssen** [docker/labs#208]
On https://github.com/docker/labs/blob/master/developer-tools/java/chapters/ch03-build-image.adoc the text below is present. However the specific build command is not mentioned. I guess it should be 'docker build -t helloworld .'.

This image uses ubuntu as the base image. CMD command defines the command that needs to run. It provides a different entry point of /bin/echo and gives the argument “hello world”.

Build the image:

**Comment by ManoMarks** [comment]
@arun-gupta can you take a look?

**Comment by arun-gupta** [comment]
Sent a PR: https://github.com/docker/labs/pull/209
