### ISSUE TITLE
Typo in Readme.adoc for Java For Developers Lab 

### ISSUE THREAD

**Issue by jpham247** [docker/labs#21]
In [Java_For_Developers_Main_Readme](https://github.com/docker/labs/blob/master/java/readme.adoc)

Link to [Docker Basic Concepts](https://github.com/docker/labs/blob/master/java/chapters/ch02-basic-concepts.adoc) does not work due to incorrectly named file : 
https://github.com/docker/labs/tree/master/java/chapters/ch02-basic-conceps.adoc

**Comment by ManoMarks** [comment]
Fix in #34
