### ISSUE TITLE
cAdvisor run command is not working properly

### ISSUE THREAD

**Issue by johanjanssen** [docker/labs#211]
The run command on https://github.com/docker/labs/blob/master/developer-tools/java/chapters/ch10-monitoring.adoc is not working well. It starts the container and cAdvisor, but the running containers are not visible in the webinterface of cAdvisor.

The correct command (from https://github.com/google/cadvisor) :
docker run \
  --volume=/:/rootfs:ro \
  --volume=/var/run:/var/run:rw \
  --volume=/sys:/sys:ro \
  --volume=/var/lib/docker/:/var/lib/docker:ro \
  --publish=8080:8080 \
  --detach=true \
  --name=cadvisor \
  google/cadvisor:latest

**Comment by ManoMarks** [comment]
@arun-gupta can you comment?

**Comment by arun-gupta** [comment]
@johanjanssen have you verified that the command listed above works? Are you able to see the running containers in the web interface that way?

**Comment by johanjanssen** [comment]
Yes I tested the command and I can see the containers in the web interface.

Op 29 mrt. 2017 7:32 p.m. schreef "Arun Gupta" <notifications@github.com>:

**Comment by arun-gupta** [comment]
@johanjanssen So I just need to update the command?

**Comment by johanjanssen** [comment]
Exactly just use the new command which I copied from the cAdvisor GitHub.
At least one volume was missing in the original command that's why it
didn't work.

Op 29 mrt. 2017 8:19 p.m. schreef "Arun Gupta" <notifications@github.com>:

**Comment by arun-gupta** [comment]
@ManoMarks fixed, need to get PR merged.

**Comment by ManoMarks** [comment]
Thanks!
