### ISSUE TITLE
standard_init_linux.go:178: exec user process caused "no such file or directory"

### ISSUE THREAD

**Issue by GingerMoon** [docker/labs#215]
**Which lab is it that you're having issues with?**
In-container Java Development: IntelliJ Community Edition
https://github.com/docker/labs/blob/master/developer-tools/java-debugging/IntelliJ-README.md

**Description**

I got the error below after running the command: docker-compose up
webserver_1  | standard_init_linux.go:178: exec user process caused "no such file or directory"

**Steps to reproduce the issue, if relevant:**
Do the same as described in the link:
https://github.com/docker/labs/blob/master/developer-tools/java-debugging/IntelliJ-README.md
But is blocked at:
Running the application
Open a terminal and go to the application directory. Start the application with docker-compose
> docker-compose up 

**Describe the results you received:**
webserver_1  | standard_init_linux.go:178: exec user process caused "no such file or directory"

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

Docker version 17.03.1-ce, build c6d412e
Windows10 Enterprise
![default](https://cloud.githubusercontent.com/assets/8342412/24536946/e0ae5200-1610-11e7-9a40-556252ce09e3.png)

**Comment by GingerMoon** [comment]
Tried with 
git clone https://github.com/spara/registration-docker.git --config core.autocrlf=input
Still doesn't work.

**Comment by ManoMarks** [comment]
@GingerMoon were you in the root of the application directory when you ran ```docker-compose up```? Here's what it looks like for me:
![screen shot 2017-03-31 at 12 35 50 pm](https://cloud.githubusercontent.com/assets/113855/24566530/b1f08480-160e-11e7-8b6b-4ae1a913d038.png)

**Comment by GingerMoon** [comment]
@ManoMarks Thank you very much for the prompt response!
git clone https://github.com/spara/registration-docker.git --config core.autocrlf=input
![default](https://cloud.githubusercontent.com/assets/8342412/24573840/1cb486a6-16bc-11e7-8002-e0877d035f6f.png)

**Comment by GingerMoon** [comment]
Hi guys,
Any update?

Regards,

**Comment by spara** [comment]
Hi GingerMoon,

I was able to replicate your problem which is the LF character in dos/cygwin/Powershell is converted to CRLF when the repo is pushed to github. This occurs on a Windows 10 machine in either the Windows git client or Powershell.  Use dos2unix to fix the affected files

```
dos2unix  ../labs/developer-tools/java-debugging/registration-webserver/tomcat/tomcat-users.xml
dos2unix  ../labs/developer-tools/java-debugging/registration-webserver/tomcat/run.sh
```

**Comment by GingerMoon** [comment]
Hi spara,
Thank you for your reply. It doesn't work.
![default](https://cloud.githubusercontent.com/assets/8342412/25693292/f61b9d84-30da-11e7-8e6d-b2af8f9d663b.png)

**Comment by GingerMoon** [comment]
@spara

**Comment by spara** [comment]
Did you rebuild the containers to use the files that were changed?
```
docker-compose up --build
```

**Comment by GingerMoon** [comment]
many thanks!

**Comment by meteoric9637** [comment]
Hi GingerMoon, did you solve the problem?

**Comment by spara** [comment]
How to run tutorial in Windows:

```
dos2unix  ../labs/developer-tools/java-debugging/registration-webserver/tomcat/tomcat-users.xml
dos2unix  ../labs/developer-tools/java-debugging/registration-webserver/tomcat/run.sh
docker-compose up --build
```

**Comment by liwei-box** [comment]
it's aused by git for windows, line breaks are forced to dos format
step 1: git config --global core.autocrlf false
step 2: delete code and git clone again

**Comment by jchavannes** [comment]
I am having similar issue:
```
standard_init_linux.go:195: exec user process caused "no such file or directory"
```
This error message doesn't give me much of a clue what might be the error.  Been struggling for a few hours to try to fix but don't really even know where to start :(

**Comment by spara** [comment]
Which operating system are you using and what version of Docker?

**Comment by jchavannes** [comment]
@spara Mac and Docker for Mac, version 17.12.0-ce-rc2-mac41 (21193).

I have a go binary and am using `FROM scratch`.  It works for a hello world binary, but when I put a more complicated one in there I get this error.

**Comment by spara** [comment]
Can you post your Dockerfile?

**Comment by jchavannes** [comment]
```
FROM scratch
ADD main /
CMD ["/main"]
```

**Comment by spara** [comment]
OK, I see the problem. You're probably building your go binary on the Mac and trying to run it in Linux container. Try this when building your go binary:

env GOOS=linux GOARCH=386 go build hello-world.go

**Comment by jchavannes** [comment]
I'm building using the `golang:1.8` docker container.  Like I said, hello world works, I'm only having this issue with a larger project.  Also, the binary I'm building works in an Ubuntu container, so I know it's building for linux just fine.

I'm also using `CGO_ENABLED=0` and have tried adding `-ldflags '-w -extldflags "-static"'` to ensure it doesn't have any dependencies.

And even so, if the binary was built incorrectly, why would it give an error that it cannot find the file?

**Comment by ManoMarks** [comment]
I don't think this is related to a specific lab we have on this repo @jchavannes, is it? The lab originally referred to was a Java debugging in IntelliJ lab. I realize this comes up second in the Google search for `standard_init_linux.go:178: exec user process caused "no such file or directory" docker` but if it's not related to one of these labs, I suggest you try the Docker Forums (https://forums.docker.com/) or the Docker Community Slack (https://community.docker.com).

**Comment by jchavannes** [comment]
Ok, thanks..

**Comment by Jacksonary** [comment]
Hi GingerMoon，I have same trouble with you,have you deal with it?

**Comment by Jacksonary** [comment]
@GingerMoon

**Comment by hafah** [comment]
maybe its the crlf on all your files.
```
git config --global core.eol lf
git config --global core.autocrlf input
find . -type f -print0 | xargs -0 dos2unix
```

**Comment by anshupitlia** [comment]
@jchavannes Hey I am facing the same issue, were you able to solve it?

**Comment by jchavannes** [comment]
@anshupitlia nope, I was not able to solve it and gave up on `FROM scratch` containers :/

Btw, I ended up posting this question on docker forums as well - https://forums.docker.com/t/standard-init-linux-go-195-exec-user-process-caused-no-such-file-or-directory/43777

**Comment by Jacksonary** [comment]
I didn't do anything, and suddenly it disappeared.Maybe it cause by the format of  dos, you must be format it to Unix
发送自 Windows 10 版邮件应用

发件人: anshupitlia
发送时间: 2018年1月20日 4:55
收件人: docker/labs
抄送: jacksonary; Mention
主题: Re: [docker/labs] standard_init_linux.go:178: exec user processcaused "no such file or directory" (#215)

@jchavannes Hey I am facing the same issue, were you able to solve it?

**Comment by winex01** [comment]
@jchavannes i have the same problem. did you solve it?

**Comment by oranheim** [comment]
Experiencing the same issue with Docker engine 17.12.0-ce on Windows 10. The image that fails is built using FROM openjdk:8-alpine.

**Comment by aguilita1** [comment]
@oranheim I was able to resolve issue by adjust LF setting with GIT (See below), remove git repo, and then rebuilding from fresh repo.
```
git config --global core.eol lf
git config --global core.autocrlf input
```

**Comment by oranheim** [comment]
Will this be fixed in a coming release?

**Comment by ManoMarks** [comment]
I'm locking this issue going forward. Please migrate discussions/bugs to https://github.com/docker/for-linux, https://github.com/docker/for-mac, https://github.com/docker/for-win or https://github.com/moby/moby
this repo is for Docker labs and the comments here are not directly related to the labs.
