### ISSUE TITLE
Error response from daemon: No such container: static-site

### ISSUE THREAD

**Issue by livier92** [docker/labs#217]
I am having an issue with this lab [2.0 Webapps with Docker](https://github.com/docker/labs/blob/master/beginner/chapters/webapps.md)

In section 2.1 after performing this two commands:

> But first, let's stop and remove the containers since you won't be using them anymore.

```
$ docker stop static-site
$ docker rm static-site
```

the tutorial goes on and says to perform this:

> Let's use a shortcut to remove the second site:

`$ docker rm -f static-site static-site-2`

The terminal outputs the following error

`Error response from daemon: No such container: static-site
`

I expected to receive no error from the terminal. 

The tutorial should rewrite that section better so that it is clear to either remove the two static-sites with the first two commands **OR** use the shortcut to remove the two sites with one command only.

```
Docker version 17.03.0-ce, build 60ccb22
```

**Comment by itspritish** [comment]
minor doc correction- https://github.com/docker/labs/pull/219
