### ISSUE TITLE
missing cd helloworld after cloning from https://github.com/arun-gupta/docker-java-sample/

### ISSUE THREAD

**Issue by giorgioongithub** [docker/labs#22]
Package and Run Java Application using Docker Maven Plugin

after cloning you have to do:

cd docker-java-sample
cd helloworld
mvn package -Pdocker

not just 
cd docker-java-sample
mvn package -Pdocker

because the pom.xml is on the hello world subdirectory

**Comment by ManoMarks** [comment]
Fix in #34
