### ISSUE TITLE
Error connection refused

### ISSUE THREAD

**Issue by livier92** [docker/labs#223]
Lab having issues with: 3.0 Deploying an app to a Swarm

**Description**
After creating the swarm, the tutorial says

> Next, you will need a Docker Compose file. You don't need Docker Compose installed, though if you are using Docker for Mac or Docker for Windows you have it installed.

I am using Ubuntu 14.04, so  I thought I don't needed Docker-compose. However, when I was trying to access the [results](http://localhost:5001) page, it said:

> ERR_CONNECTION_REFUSED

So, I decided to install Docker Compose and that solved my problem. Just a heads up to update the documentation, it seems that Docker Compose is NEEDED regardless of the OS being used.

**Comment by ManoMarks** [comment]
Sorry to just get to this, DockerCon slowed a lot down. This should NOT be true. Can you confirm the results of `docker version`?

**Comment by ManoMarks** [comment]
@livier92 closing this issue as there's no more information incoming. However, if you can provide reproduction steps and `docker version` information please post an issue here: https://github.com/moby/moby
