### ISSUE TITLE
Java Chapter 2: Only Toolbox-based installations have a default machine entry

### ISSUE THREAD

**Issue by padyx** [docker/labs#23]
In[ Chapter 2 of the Java](https://github.com/docker/labs/blob/master/java/chapters/ch02-basic-conceps.adoc) under the section "Verify Docker Configuration" it is written that calling `docker-machine ls` will show an entry named "default".

However, when you have a Linux installation (say Ubuntu), docker will not run using Toolbox with a default (virtualbox) instance. I am unsure if that would also be the case with the new Docker Beta.

The document should be amended to reflect that. For example:

> On operating systems that run Docker natively without running Virtalbox, such as Linux, there is no default entry.

**Comment by ManoMarks** [comment]
@arun-gupta this is another one to update
