### ISSUE TITLE
Fix the link to Compose file in setup

### ISSUE THREAD

**Issue by arun-gupta** [docker/labs#239]
Fix the link in https://github.com/docker/labs/blob/master/developer-tools/java/chapters/ch01-setup.adoc from https://github.com/docker/labs/blob/master/developer-tools/java/scripts/docker-compose-pull-images.yml to https://raw.githubusercontent.com/docker/labs/master/developer-tools/java/scripts/docker-compose-pull-images.yml

#DockerCon

**Comment by ManoMarks** [comment]
@arun-gupta

**Comment by arush-sal** [comment]
Fixed in PR #289

**Comment by arun-gupta** [comment]
PR merged and the issue can be closed.
