### ISSUE TITLE
Java Chapter 06: bad instructions for connecting to swarm for windows

### ISSUE THREAD

**Issue by ddefolo** [docker/labs#24]
https://github.com/docker/labs/blob/master/java/chapters/ch06-swarm.adoc#Connect_to_Docker_Swarm_Cluster mentions the following for connecting to swarm:

> If you’re on Windows, then use the  docker-machine env --swarm swarm-master  command only. Then copy the output into an editor to replace all appearances of EXPORT with SET, remove the quotes, and all appearances of "/" with "\". Finally, issue the three commands at your command prompt.

This changing from export to set and changing to \ doesn't seem to help as the docker toolbox is a git for windows bash shell (not windows cmd) so it understands export statements not set.

If you are running the current version of docker Toolbox for windows the output of the docker-machine env command actually provides the valid eval statement:

```
$  docker-machine env --swarm swarm-master
export DOCKER_TLS_VERIFY="1"
export DOCKER_HOST="tcp://192.168.99.102:3376"
export DOCKER_CERT_PATH="C:\Users\ddefolo\.docker\machine\machines\swarm-master"
export DOCKER_MACHINE_NAME="swarm-master"
# Run this command to configure your shell:
# eval $("C:\Program Files\Docker Toolbox\docker-machine.exe" env --swarm swarm-master)
```
After doing the following docker info showed the swarm info:
`eval $("C:\Program Files\Docker Toolbox\docker-machine.exe" env --swarm swarm-master)`

**Comment by StefanScherer** [comment]
Yes, docker-machine.exe is able to output the correct instructions for CMD, PowerShell and other unixish shells.

**Comment by ManoMarks** [comment]
@arun-gupta we should probably update this to use Docker for Mac/Docker for Windows instead of Machine, with pointers to the Machine documentation for people on earlier versions of Windows.

**Comment by arun-gupta** [comment]
This issue can be closed now.
