### ISSUE TITLE
ch 3 typo

### ISSUE THREAD

**Issue by maspen** [docker/labs#240]
Chapter 3 -

https://github.com/docker/labs/blob/master/developer-tools/java/chapters/ch03-build-image.adoc#difference-between-cmd-and-entrypoint

'TL;DR CMD will work for most of the cases.' - Notice "TL:DR"

https://github.com/docker/labs/blob/master/developer-tools/java/chapters/ch03-build-image.adoc#difference-between-add-and-copy

'TL;DR COPY will work for most of the cases.' - similar to above ...

**Comment by ManoMarks** [comment]
@arun-gupta

**Comment by arun-gupta** [comment]
@maspen @arush-sal evaluation seems correct. Let us know if you were referring to something else.

@ManoMarks No change required here, issue can be closed.
