### ISSUE TITLE
Upgrade to experimental does not seem to be clearly defined.

### ISSUE THREAD

**Issue by jdaehn** [docker/labs#245]
@arun-gupta Upgrade to experimental does not seem to be clearly defined.

Toggling the Daemon experimental checkbox in the Docker preferences dialog on my Mac seemed to have no affect. That is, 

```
$ docker info
...
Experimental: false
...
```

Didn't change. This is true whether we manually modify the daemon config file under the Advanced tab or just toggling the checkbox under the Basic tab.

**Comment by jdaehn** [comment]
This may be related to the fact that I had the default docker machine running. I noticed that when I shut that down and reset the DOCKER* environment variables, this no longer seemed to be an issue. In other words, I'm not sure if it's a bug or operator error. Regardless, it may be useful information to state in and around the material that discusses how to set the experimental flag to true.

**Comment by arun-gupta** [comment]
Valid issue but the workshop will only use Docker CE going forward. No instructions for Docker Toolbox will be provided.

@ManoMarks this can be closed.
