### ISSUE TITLE
Slightly wrong command in "Deploy Application user Swarm Mode"

### ISSUE THREAD

**Issue by allan-d-c** [docker/labs#246]
** PLEASE ONLY USE THIS ISSUE TRACKER TO SUBMIT ISSUES WITH THE DOCKER LABS TUTORIAL CONTENT **

* If you have a bug working with Docker itself, not related to these labs, please file the bug on the [Docker repo](https://github.com/docker/docker) *
* If you would like general support figuring out how to do something with Docker, please use the Docker Slack channel. If you're not on that channel, sign up for the [Docker Community](http://dockr.ly/MeetUp) and you'll get an invite. *
* Or go to the [Docker Forums](https://forums.docker.com/) *

Please provide the following information so we can assess the issue you're having

**Which lab is it that you're having issues with?**

**Description**

In the subsection "Stop Application", the command

docker service scale webapp_db=0 webapp_web=0 webapp_default=0

should not have the webapp_default=0 because that is the network. It gives an 
innocuous error "no such service". The command should be

docker service scale webapp_db=0 webapp_web=0

**Steps to reproduce the issue, if relevant:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, Docker for Mac, Docker for Windows, VirtualBox, physical, etc.):**

**Comment by ManoMarks** [comment]
Which lab does this issue reference?

**Comment by allan-d-c** [comment]
Docker for Java Developers

**Comment by ManoMarks** [comment]
@arun-gupta

**Comment by arun-gupta** [comment]
No longer an issue, a different/simpler application is now used. @ManoMarks can now be closed.
