### ISSUE TITLE
Docker For AWS SSH Tunnel needs -o StrictHostKeyChecking=no

### ISSUE THREAD

**Issue by 0xMackenzie** [docker/labs#247]
Without the StrictHostKeyChecking option, you cannot place the ssh tunnel in the background the first time because you would need to respond to the key check. 

The example should be:
 `ssh -i ~/.ssh/arun-cb-west2.pem   -o StrictHostKeyChecking=no -NL localhost:2374:/var/run/docker.sock docker@ec2-52-37-65-169.us-west-2.compute.amazonaws.com &
`

@arun-gupta

**Comment by arun-gupta** [comment]
Fixed, @ManoMarks can be closed
