### ISSUE TITLE
Chapter 4 - Accessing WildFly gives Connection Refused Error

### ISSUE THREAD

**Issue by bcoveny** [docker/labs#249]
** PLEASE ONLY USE THIS ISSUE TRACKER TO SUBMIT ISSUES WITH THE DOCKER LABS TUTORIAL CONTENT **

* If you have a bug working with Docker itself, not related to these labs, please file the bug on the [Docker repo](https://github.com/docker/docker) *
* If you would like general support figuring out how to do something with Docker, please use the Docker Slack channel. If you're not on that channel, sign up for the [Docker Community](http://dockr.ly/MeetUp) and you'll get an invite. *
* Or go to the [Docker Forums](https://forums.docker.com/) *

Please provide the following information so we can assess the issue you're having

**Which lab is it that you're having issues with?**

developer-tools/java/chapters/ch04-run-container.adoc

Chapter 4 - Run a Docker Container

**Description**

Cannot connect to WildFly Server once started on exact ports mentioned in docker container

**Steps to reproduce the issue, if relevant:**
1.  Start default WildFly container
2.  run docker containers ps to obtain port
3.  hit localhost:32768/

**Describe the results you received:**

Received localhost connection refused

**Describe the results you expected:**

Expected to see WildFly default home page.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Tue Mar 28 00:40:02 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.04.0-ce
 API version:  1.28 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Wed Apr  5 18:45:47 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 17
Server Version: 17.04.0-ce
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 106
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary:
containerd version: 422e31ce907fd9c3833a38d7b8fdd023e5a76e73
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.4.59-boot2docker
Operating System: Boot2Docker 17.04.0-ce (TCL 7.2); HEAD : c69677f - Thu Apr  6 16:26:16 UTC 2017
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.955 GiB
Name: default
ID: GYO4:6KEI:DWLS:H2BK:QDUN:VJ4W:ZU76:ACBL:5UT7:OAH3:562W:OIUT
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 14
 Goroutines: 23
 System Time: 2017-04-17T20:59:06.197849507Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, Docker for Mac, Docker for Windows, VirtualBox, physical, etc.):**

DockerToolbox for Windows
Virtual Box running
Windows 7

**RESOLUTION**
Instead of hitting localhost for communicating with any docker started service it was necessary to use the preconfigured "dockerhost" done in the hosts file of windows.  Once changed to dockerhost:32768 then the page was displayed.

**Comment by ManoMarks** [comment]
@arun-gupta

**Comment by arun-gupta** [comment]
The lab will use Docker CE going forward and not Docker Toolbox. This bug will not be fixed. 

@ManoMarks can be closed.
