### ISSUE TITLE
Swarm Stack Introduction - Not Understandable

### ISSUE THREAD

**Issue by DanJ210** [docker/labs#255]
http://training.play-with-docker.com/swarm-stack-intro/

This tutorial right here the first command is `docker swarm init --advertise-addr $(hostname -i)` which gives an error static that 
`sethostname: Use the Network Control Panel Applet to set hostname.
hostname -s is not support. 
flag needs and argument: --advertise-addr 
See'docker swarm init--help'.`

I truly have no idea what the Network Control Panel Applet is. I was able to run `docker swarm init` which seems to create only 1 node not two like the tutorial says should be happening so I'm trying to figure out what else I can do here but the above command needs a little more elaboration in a tutorial.

Also, I have never gotten the "in browser" terminal to work on any browser that I've used so far. I'm using my own terminal.

**Comment by DanJ210** [comment]
I'm also trying to join with the token given to me... I am very new at this which is why I'm using the tutorial... But this command gives error even though `docker swarm join --help` shows that it should be correct.

`docker swarm join --token SWMTKN-1-1hzttrxqlqxndet2z2iyolj8fsk2kvsf3edsaot2z7orzt1uuf-1g3hfseogqppixdtgbx99cf2n` states that `docker swarm join` accepts only one argument. Well `--token` by itself isn't right and the string by itself isn't right... What am I not understanding here?

Thanks in advance.

**Comment by ManoMarks** [comment]
Please file this issue here: https://github.com/franela/franela.github.io/issues

**Comment by DanJ210** [comment]
@ManoMarks Thanks
