### ISSUE TITLE
Swarm Mode with Docker for AWS

### ISSUE THREAD

**Issue by ManoMarks** [docker/labs#264]

**Comment by arun-gupta** [comment]
This is already explained at https://github.com/docker/labs/blob/master/developer-tools/java/chapters/ch08-aws.adoc. What else were you planning to add?

I'm planning to rev all the content for DockerCon EU anyway.

**Comment by ManoMarks** [comment]
This was a generic, not Java specific lab.

**Comment by arun-gupta** [comment]
OK, feel free to assign this to me, will be happy to contribute.

**Comment by ManoMarks** [comment]
I can't assign it to you since you're not in the Docker Org, but consider this your assignment

**Comment by arun-gupta** [comment]
ok

**Comment by arun-gupta** [comment]
@ManoMarks what would you like to be covered in this, in addition to the existing content?
