### ISSUE TITLE
how to monitor JVM heartbeat using Prometheus

### ISSUE THREAD

**Issue by narsing1984** [docker/labs#266]
** PLEASE ONLY USE THIS ISSUE TRACKER TO SUBMIT ISSUES WITH THE DOCKER LABS TUTORIAL CONTENT **

* If you have a bug working with Docker itself, not related to these labs, please file the bug on the [Docker repo](https://github.com/docker/docker) *
* If you would like general support figuring out how to do something with Docker, please use the Docker Slack channel. If you're not on that channel, sign up for the [Docker Community](http://dockr.ly/MeetUp) and you'll get an invite. *
* Or go to the [Docker Forums](https://forums.docker.com/) *

Please provide the following information so we can assess the issue you're having

**Which lab is it that you're having issues with?**

**Description**

**Steps to reproduce the issue, if relevant:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, Docker for Mac, Docker for Windows, VirtualBox, physical, etc.):**

**Comment by ManoMarks** [comment]
@narsing1984 are you requesting an answer or a new lab? This repo is only for labs such as you see here: https://github.com/docker/labs/tree/master/beginner

If you're requesting an answer, please head to the Docker Community Forums: https://forums.docker.com/

**Comment by ManoMarks** [comment]
Closing since there's no additional information
