### ISSUE TITLE
Push from Windows Server 2016 gives "Access to resource is denied"

### ISSUE THREAD

**Issue by Vacant0mens** [docker/labs#270]
Please provide the following information so we can assess the issue you're having

**Which lab is it that you're having issues with?**
Registry

**Description**
On a local VM running Windows Server 2016
I followed all instructions but when I went to run "docker push [image]" it gave me this:
`6420320254ef: Preparing`
`7d9d3ca2532e: Preparing`
`b1d6808e92c7: Preparing`
`b006f9cbd337: Preparing`
`37b42a01822a: Preparing`
`32066d4eea6d: Skipped foreign layer`
`6c357baed9f5: Skipped foreign layer`
`denied: requested access to the resource is denied`

**Steps to reproduce the issue, if relevant:**
1. Followed instructions up to "docker tag" command, everything seemed fine.
2. ran docker push.

**Describe the results you expected:**
it should have pushed the image layers successfuly.

**Output of `docker version`:**

Client:
 Version:      17.03.1-ee-3
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   3fcee33
 Built:        Thu Mar 30 19:31:22 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.03.1-ee-3
 API version:  1.27 (minimum version 1.24)
 Go version:   go1.7.5
 Git commit:   3fcee33
 Built:        Thu Mar 30 19:31:22 2017
 OS/Arch:      windows/amd64
 Experimental: false
**Output of `docker info`:**
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 13
Server Version: 17.03.1-ee-3
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: l2bridge l2tunnel nat null overlay transparent
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 14393 (14393.1066.amd64fre.rs1_release_sec.170327-1835)
Operating System: Windows Server 2016 Standard
OSType: windows
Architecture: x86_64
CPUs: 2
Total Memory: 3 GiB
Name: ########
ID: UP2S:BCZ2:LR3A:ZJ7Y:AIT3:KQM2:OIJ3:VUBD:67RQ:LQLB:3COA:L43J
Docker Root Dir: E:\Docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 172.30.230.233:5000
 127.0.0.0/8
Live Restore Enabled: false

**Comment by Vacant0mens** [comment]
after re-registering the docker instance, and running "registry.exe serve config.yml" in a powershell window, i get this:
`891d432cfb7e: Retrying in 1 second
ccad70a34786: Retrying in 1 second
8f464e258fdc: Retrying in 1 second
fc76cda25330: Retrying in 1 second
05a10dd29d54: Retrying in 1 second
bd947c638a37: Waiting
ba12c784c01d: Waiting
0a844930636b: Waiting
32066d4eea6d: Waiting
6c357baed9f5: Waiting`


and in the console for registry.exe, i get this:
`::1 - - [09/May/2017:17:00:50 -0600] "GET /v2/ HTTP/1.1" 503 125 "" "docker/17.03.1-ee-3 go/go1.7.5 git-commit/3fcee33 os/windows arch/amd64 UpstreamClient(Docker-Client/17.03.1-ee-3 \\(windows\\))"
::1 - - [09/May/2017:17:01:00 -0600] "POST /v2/125/gps.application.web/blobs/uploads/ HTTP/1.1" 503 125 "" "docker/17.03.1-ee-3 go/go1.7.5 git-commit/3fcee33 os/windows arch/amd64 UpstreamClient(Docker-Client/17.03.1-ee-3 \\(windows\\))"
::1 - - [09/May/2017:17:01:00 -0600] "POST /v2/125/gps.application.web/blobs/uploads/ HTTP/1.1" 503 125 "" "docker/17.03.1-ee-3 go/go1.7.5 git-commit/3fcee33 os/windows arch/amd64 UpstreamClient(Docker-Client/17.03.1-ee-3 \\(windows\\))"
::1 - - [09/May/2017:17:01:00 -0600] "POST /v2/125/gps.application.web/blobs/uploads/ HTTP/1.1" 503 125 "" "docker/17.03.1-ee-3 go/go1.7.5 git-commit/3fcee33 os/windows arch/amd64 UpstreamClient(Docker-Client/17.03.1-ee-3 \\(windows\\))"
::1 - - [09/May/2017:17:01:00 -0600] "POST /v2/125/gps.application.web/blobs/uploads/ HTTP/1.1" 503 125 "" "docker/17.03.1-ee-3 go/go1.7.5 git-commit/3fcee33 os/windows arch/amd64 UpstreamClient(Docker-Client/17.03.1-ee-3 \\(windows\\))"
::1 - - [09/May/2017:17:01:00 -0600] "POST /v2/125/gps.application.web/blobs/uploads/ HTTP/1.1" 503 125 "" "docker/17.03.1-ee-3 go/go1.7.5 git-commit/3fcee33 os/windows arch/amd64 UpstreamClient(Docker-Client/17.03.1-ee-3 \\(windows\\))"
::1 - - [09/May/2017:17:01:05 -0600] "POST /v2/125/gps.application.web/blobs/uploads/ HTTP/1.1" 503 125 "" "docker/17.03.1-ee-3 go/go1.7.5 git-commit/3fcee33 os/windows arch/amd64 UpstreamClient(Docker-Client/17.03.1-ee-3 \\(windows\\))"
::1 - - [09/May/2017:17:01:05 -0600] "POST /v2/125/gps.application.web/blobs/uploads/ HTTP/1.1" 503 125 "" "docker/17.03.1-ee-3 go/go1.7.5 git-commit/3fcee33 os/windows arch/amd64 UpstreamClient(Docker-Client/17.03.1-ee-3 \\(windows\\))"
::1 - - [09/May/2017:17:01:05 -0600] "POST /v2/125/gps.application.web/blobs/uploads/ HTTP/1.1" 503 125 "" "docker/17.03.1-ee-3 go/go1.7.5 git-commit/3fcee33 os/windows arch/amd64 UpstreamClient(Docker-Client/17.03.1-ee-3 \\(windows\\))"
::1 - - [09/May/2017:17:01:05 -0600] "POST /v2/125/gps.application.web/blobs/uploads/ HTTP/1.1" 503 125 "" "docker/17.03.1-ee-3 go/go1.7.5 git-commit/3fcee33 os/windows arch/amd64 UpstreamClient(Docker-Client/17.03.1-ee-3 \\(windows\\))"
::1 - - [09/May/2017:17:01:05 -0600] "POST /v2/125/gps.application.web/blobs/uploads/ HTTP/1.1" 503 125 "" "docker/17.03.1-ee-3 go/go1.7.5 git-commit/3fcee33 os/windows arch/amd64 UpstreamClient(Docker-Client/17.03.1-ee-3 \\(windows\\))"`

**Comment by Vacant0mens** [comment]
Update:
I changed the config.yml to have a valid storage folder. Running in a powershell window now works, which solves the 503's in my second comment, but I would still like to know where I went wrong in the first place.

**Comment by spara** [comment]
Hi,

Is the image you are trying to push available? I'm unable to replicate this error.

**Comment by Vacant0mens** [comment]
The image was created on the server I was pushing from. But it was an issue with building the docker image for the registry. Once I scrapped trying to build the image and used an image posted by @sixeyed it worked fine.
