### ISSUE TITLE
Error in 2.0 Webapps with Docker:  No push without first doing a login from CLI.

### ISSUE THREAD

**Issue by zipzit** [docker/labs#285]
** PLEASE ONLY USE THIS ISSUE TRACKER TO SUBMIT ISSUES WITH THE DOCKER LABS TUTORIAL CONTENT **

Please provide the following information so we can assess the issue you're having

**Which lab is it that you're having issues with?**

2.0 Webapps with Docker, specifically 2.3.4, Push your image (https://github.com/docker/labs/blob/master/beginner/chapters/webapps.md#234-push-your-image)

**Description**

The instructions to push to docker.com are not complete.  There is no way to successfully push via `$ docker push userName/appname:tagname` You will get an error: `denied: requested access to the resource is denied`

The fix is to login from the command line via `docker login`  ( and respond to login/password prompts) BEFORE you attempt to `$ docker push...`

The instructions don't mention the requirement to login anywhere.  Possible to get the instructions updated to so state?  (and if I missed it, somehow, somewhere, apologies...)

**Steps to reproduce the issue, if relevant:**
1.  Follow the tutorial for the flask app as written.  
2.  When you try to push to docker repository, it will fail with `denied: requested access to the resource is denied`
3. Have a nice day.  

**Describe the results you received:**

**Describe the results you expected:**
Push to repository success at https://cloud.docker.com/swarm
Command line success = `latest: digest: sha256:683c6a4a57e45410dc456e19f8fa91ce91dcb37d40e902a509263fa9a402b273 size: 1572` or words to that effect.  

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
$ docker version
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Tue Mar 28 00:40:02 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Fri Mar 24 00:00:50 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 8
Server Version: 17.03.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.27-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 3.855 GiB
Name: moby
ID: 64QX:5SAC:Z5FR:PLJ6:DKGZ:CTOY:JCJG:KF4X:23J6:B4I6:UTM2:AZRP
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 25
 Goroutines: 40
 System Time: 2017-05-30T08:30:50.130189887Z
 EventsListeners: 2
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, Docker for Mac, Docker for Windows, VirtualBox, physical, etc.):**

**Comment by bhavin192** [comment]
You are right, when I tried this lab, I faced the same issue. I have fixed this can you have a look [here ](https://github.com/bhavin192/labs/blob/8b0dbd5d252e36a67167b2b2acb623a1e9c6b563/beginner/chapters/webapps.md)

**Comment by zipzit** [comment]
bhavin192

Nicely done! thanks.
