### ISSUE TITLE
security-opt in docker file and swarm 

### ISSUE THREAD

**Issue by sujjit1991** [docker/labs#290]
I am trying to add "security-opt" option in docker build file (Dockerfile), do we have any INSTRUCTION for that?

I am using the stack.Yaml file in docker swarm to deploy the services, stack.yml doesn't support the security-opt feature in the swarm, if I want to use the AppArmor and seccomp profiles in the swarm, is there any way to use it?

**Comment by ManoMarks** [comment]
Hi! We need a bit more info. Please use this template to give us the information we need:
** PLEASE ONLY USE THIS ISSUE TRACKER TO SUBMIT ISSUES WITH THE DOCKER LABS TUTORIAL CONTENT **

* If you have a bug working with Docker itself, not related to these labs, please file the bug on the [Docker repo](https://github.com/moby/moby) *
* If you would like general support figuring out how to do something with Docker, please use the Docker Slack channel. If you're not on that channel, sign up for the [Docker Community](http://dockr.ly/MeetUp) and you'll get an invite. *
* Or go to the [Docker Forums](https://forums.docker.com/) *

Please provide the following information so we can assess the issue you're having

**Which lab is it that you're having issues with?**


**Description**



**Steps to reproduce the issue, if relevant:**
1.
2.
3.

**Describe the results you received:**


**Describe the results you expected:**


**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, Docker for Mac, Docker for Windows, VirtualBox, physical, etc.):**
