### ISSUE TITLE
Part 1 -  Unknown instruction: CP

### ISSUE THREAD

**Issue by chandandattahlk** [docker/labs#295]
I am trying to go through the labs on a Windows Server 2016 machine, but have several roadblocks.

Windows version:  Windows server standard 2016 version 1607 Build 14393.1198
```
Docker version: 
Client:
 Version:      17.03.1-ee-3
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   3fcee33
 Built:        Thu Mar 30 19:31:22 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.03.1-ee-3
 API version:  1.27 (minimum version 1.24)
 Go version:   go1.7.5
 Git commit:   3fcee33
 Built:        Thu Mar 30 19:31:22 2017
 OS/Arch:      windows/amd64
 Experimental: false
```

I tried following the [instructions](https://github.com/docker/labs/blob/master/windows/registry/part-1.md) in lab part 1 and got this error

```
PS C:\work\goWorkspace> docker build -t registry-builder -f .\Dockerfile.build .
Sending build context to Docker daemon 3.668 MB
Error response from daemon: Unknown instruction: CP
```

When I changed the command from CP to COPY, I got this error:

```
Step 2/5 : SHELL powershell -Command $ErrorActionPreference = 'Stop';
 ---> Running in bb81151da54e
 ---> c8c4f807fd51
Removing intermediate container bb81151da54e
Step 3/5 : CMD .\go get github.com/docker/distribution/cmd/registry ; `
 ---> Running in afc8df13f5d9
 ---> ce4e2e4a1bb4
Removing intermediate container afc8df13f5d9
Step 4/5 : COPY \"$env:GOPATH\bin\registry.exe\" c:\out\ ; `
Forbidden path outside the build context: ":GOPATHbinregistry.exe" ()
```

I then compiled the Go code on the local machine and tried part 2 without the build container, but the docker service restart failed.

```
PS C:\work\goWorkspace> Stop-Service docker
PS C:\work\goWorkspace> dockerd --unregister-service
PS C:\work\goWorkspace> dockerd --register-service  -G docker -H npipe:// -H 0.0.0.0:2375 --insecure-registry 172.23.52.181:5000
PS C:\work\goWorkspace> Start-Service docker
Start-Service : Failed to start service 'Docker Engine (docker)'.
At line:1 char:1
+ Start-Service docker
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (System.ServiceProcess.ServiceController:ServiceController) [Start-Service], ServiceCommandException
    + FullyQualifiedErrorId : StartServiceFailed,Microsoft.PowerShell.Commands.StartServiceCommand
```

Is there any fix and can a docker registry be built on Windows Server 2016 Standard?

**Comment by chandandattahlk** [comment]
Wondering if there's any update to this issue? Is anyone able to reproduce this

**Comment by StefanScherer** [comment]
Oh, there is a problem with trailing spaces in the markdown and Dockerfile. VSCode shows that

<img width="965" alt="bildschirmfoto 2017-11-30 um 07 27 29" src="https://user-images.githubusercontent.com/207759/33417349-6b904cfc-d5a1-11e7-8031-ba5cd6660ac4.png">

So the line continuation does not work and Docker catches the next line as "CP" instruction.
