### ISSUE TITLE
failed at step 2 

### ISSUE THREAD

**Issue by zhouchenzc0824** [docker/labs#304]
**Which lab is it that you're having issues with?**
the docker for beginers

**Description**
not be able to install python and pip saying no files found
I changed py-pip to py2-pip but still not working

**Output of `docker version`:**

```
Docker version 17.05.0-ce, build 89658be
```

**Output of `docker info`:**

```
root@vblinux:~/software/docker/flask-app# docker build -t docker/myapp .
Sending build context to Docker daemon   7.68kB
Step 1/8 : FROM alpine
 ---> 665ffb03bfae
Step 2/8 : RUN apk add --update py2-pip
 ---> Running in 9e963eb5c93c
fetch http://dl-cdn.alpinelinux.org/alpine/v3.6/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.6/community/x86_64/APKINDEX.tar.gz
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.6/main: temporary error (try again later)
WARNING: Ignoring APKINDEX.84815163.tar.gz: No such file or directory
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.6/community: temporary error (try again later)
WARNING: Ignoring APKINDEX.24d64ab1.tar.gz: No such file or directory
ERROR: unsatisfiable constraints:
  py2-pip (missing):
    required by: world[py2-pip]
The command '/bin/sh -c apk add --update py2-pip' returned a non-zero code: 1
```

**Additional environment details (AWS, Docker for Mac, Docker for Windows, VirtualBox, physical, etc.):**

**Comment by ManoMarks** [comment]
I believe this may have been a temporary problem with the alpine linux cdn. I'm unable to reproduce the error. What happens when you try again?

**Comment by zhouchenzc0824** [comment]
@ManoMarks  when i tried to do the 2.3.3 build the image with command
```
$ docker build -t <YOUR_USERNAME>/myfirstapp . 
```
It will produce the error i post.
I checked out the logs that it showed something wrong with the CDN resource but its been few days  i keep getting the same error. so confused.
my files attached.
[flask-app.zip](https://github.com/docker/labs/files/1092915/flask-app.zip)

**Comment by ManoMarks** [comment]
Even with the your Dockerfile I'm unable to reproduce it. Are you on a proxy? We've had trouble with some proxies blocking the alpine cdn.

**Comment by zhouchenzc0824** [comment]
I am not on a proxy but using WIFI at work. But I just tried at home, still get the same issue. 
BTW my machine is  windows 10  and I am running docker on Ubuntu on Virtual Box , can this be a problem?

**Comment by ManoMarks** [comment]
Could be a weird windows networking issue, or something between the VM and Windows. Are you on Windows 10Pro? You could try Docker for Windows.

**Comment by zhouchenzc0824** [comment]
I tried to run ```apt-get update``` or ``` ping Google.com``` in different Linux OS containers like CentOS, Alpine, and Ubuntu and they all failed to do so. I think the problem is that every container cannot have access to connect to the Internet. So I googled how to make container connect to Internet.  
The solution is to go to ```/etc/default/docker```  and uncomment ```DOCKER_OPTS="--dns 8.8.8.8 --dns 8.8.4.4" ```   like this 
```
# Docker Upstart and SysVinit configuration file

#
# THIS FILE DOES NOT APPLY TO SYSTEMD
#
#   Please see the documentation for "systemd drop-ins":
#   https://docs.docker.com/engine/admin/systemd/
#

# Customize location of Docker binary (especially for development testing).
# DOCKERD="/usr/local/bin/dockerd"

# Use DOCKER_OPTS to modify the daemon startup options.
  DOCKER_OPTS="--dns 8.8.8.8 --dns 8.8.4.4"

# If you need Docker to use an HTTP proxy, it can also be specified here.
# export http_proxy="http://127.0.0.1:3128/"

# This is also a handy place to tweak where Docker's temporary files go.
# export DOCKER_TMPDIR="/mnt/bigdrive/docker-tmp"
~                                                                    
```
now restart the service ``` sudo service docker restart ```   then it will work 
Got stuck for few days, thanks for this post, helped me a lot. 
http://odino.org/cannot-connect-to-the-internet-from-your-docker-containers/

**Comment by ManoMarks** [comment]
Thanks for the follow-up
