### ISSUE TITLE
Multicontainer Application Lab Doesn't Build

### ISSUE THREAD

**Issue by timomta** [docker/labs#319]
Multicontainer Application lab does not build with Docker for Windows
https://github.com/docker/labs/blob/master/windows/windows-containers/MultiContainerApp.md

The first step of the lab is
    git clone https://github.com/dockersamples/dotnet-musicstore
which works fine
The next step fails
  docker-compose -f .\docker-compose.windows.yml build

...

Step 9/15 : RUN dotnet restore --runtime win10-x64 .\samples\MusicStore
 ---> Running in 9abe65631f94
  Restoring packages for C:\MusicStore\samples\MusicStore\MusicStore.csproj...
C:\Program Files\dotnet\sdk\1.0.4\NuGet.targets(97,5): warning : Dependency specified was Microsoft.AspNetCore (>= 1.2.0
-preview1-23881) but ended up with Microsoft.AspNetCore 1.2.0-preview1-24137. [C:\MusicStore\samples\MusicStore\MusicSto
re.csproj]
C:\Program Files\dotnet\sdk\1.0.4\NuGet.targets(97,5): warning : Dependency specified was Microsoft.AspNetCore.Authentic
ation.Cookies (>= 1.2.0-preview1-23881) but ended up with Microsoft.AspNetCore.Authentication.Cookies 1.2.0-preview1-241
37. [C:\MusicStore\samples\MusicStore\MusicStore.csproj]
C:\Program Files\dotnet\sdk\1.0.4\NuGet.targets(97,5): warning : Dependency specified was Microsoft.AspNetCore.Authentic
ation.Facebook (>= 1.2.0-preview1-23881) but ended up with Microsoft.AspNetCore.Authentication.Facebook 1.2.0-preview1-2
4137. [C:\MusicStore\samples\MusicStore\MusicStore.csproj]
C:\Program Files\dotnet\sdk\1.0.4\NuGet.targets(97,5): warning : Dependency specified was Microsoft.AspNetCore.Authentic
ation.Google (>= 1.2.0-preview1-23881) but ended up with Microsoft.AspNetCore.Authentication.Google 1.2.0-preview1-24137
. [C:\MusicStore\samples\MusicStore\MusicStore.csproj]
C:\Program Files\dotnet\sdk\1.0.4\NuGet.targets(97,5): warning : Dependency specified was Microsoft.AspNetCore.Authentic
ation.MicrosoftAccount (>= 1.2.0-preview1-23881) but ended up with Microsoft.AspNetCore.Authentication.MicrosoftAccount
1.2.0-preview1-24137. [C:\MusicStore\samples\MusicStore\MusicStore.csproj]
C:\Program Files\dotnet\sdk\1.0.4\NuGet.targets(97,5): warning : Dependency specified was Microsoft.AspNetCore.Authentic
ation.OpenIdConnect (>= 1.2.0-preview1-23881) but ended up with Microsoft.AspNetCore.Authentication.OpenIdConnect 1.2.0-
preview1-24137. [C:\MusicStore\samples\MusicStore\MusicStore.csproj]

...

C:\Program Files\dotnet\sdk\1.0.4\NuGet.targets(97,5): warning :  MusicStore (>= 1.2.0-preview1) -> Microsoft.AspNetCore
 (>= 1.2.0-preview1-24137) -> Microsoft.AspNetCore.Server.Kestrel (>= 1.2.0-preview1-24137) -> System.Numerics.Vectors (
>= 4.3.0) [C:\MusicStore\samples\MusicStore\MusicStore.csproj]
C:\Program Files\dotnet\sdk\1.0.4\NuGet.targets(97,5): warning : Detected package downgrade: System.Numerics.Vectors fro
m 4.4.0-preview2-25317-01 to 4.3.0  [C:\MusicStore\samples\MusicStore\MusicStore.csproj]
C:\Program Files\dotnet\sdk\1.0.4\NuGet.targets(97,5): warning :  MusicStore (>= 1.2.0-preview1) -> Microsoft.AspNetCore
 (>= 1.2.0-preview1-24137) -> Microsoft.AspNetCore.Server.Kestrel (>= 1.2.0-preview1-24137) -> System.Text.Encodings.Web
.Utf8 (>= 0.1.0-e170706-3) -> System.Buffers.Primitives (>= 0.1.0-e170706-3) -> System.Numerics.Vectors (>= 4.4.0-previe
w2-25317-01)  [C:\MusicStore\samples\MusicStore\MusicStore.csproj]
C:\Program Files\dotnet\sdk\1.0.4\NuGet.targets(97,5): warning :  MusicStore (>= 1.2.0-preview1) -> Microsoft.AspNetCore
 (>= 1.2.0-preview1-24137) -> Microsoft.AspNetCore.Server.Kestrel (>= 1.2.0-preview1-24137) -> System.Numerics.Vectors (
>= 4.3.0) [C:\MusicStore\samples\MusicStore\MusicStore.csproj]
  Generating MSBuild file C:\MusicStore\samples\MusicStore\obj\MusicStore.csproj.nuget.g.props.
  Generating MSBuild file C:\MusicStore\samples\MusicStore\obj\MusicStore.csproj.nuget.g.targets.
  Writing lock file to disk. Path: C:\MusicStore\samples\MusicStore\obj\project.assets.json
  Restore failed in 35.91 sec for C:\MusicStore\samples\MusicStore\MusicStore.csproj.

  Errors in C:\MusicStore\samples\MusicStore\MusicStore.csproj
      Unable to resolve 'Microsoft.AspNetCore.AspNetCoreModule (>= 1.0.0-preview1-10030)' for '.NETCoreApp,Version=v1.1'
.
      Unable to resolve 'Microsoft.AspNetCore.AspNetCoreModule (>= 1.0.0-preview1-10030)' for '.NETCoreApp,Version=v1.1
(win10-x64)'.
      Unable to resolve 'Microsoft.AspNetCore.AspNetCoreModule (>= 1.0.0-preview1-10030)' for '.NETCoreApp,Version=v1.1
(win7-x64)'.

  NuGet Config files used:
      C:\MusicStore\NuGet.Config
      C:\Users\ContainerAdministrator\AppData\Roaming\NuGet\NuGet.Config

  Feeds used:
      https://dotnet.myget.org/F/aspnetcore-ci-dev/api/v3/index.json
      https://dotnet.myget.org/F/aspnetcore-tools/api/v3/index.json
      https://api.nuget.org/v3/index.json

**Comment by ManoMarks** [comment]
I'm able to reproduce the problem. Seems like there's a version upgrade needed. Assigning.

**Comment by ManoMarks** [comment]
@timomta thanks for bringing this to our attention. We've identified some problems with the music store app, looks like development has fallen behind. We have updated the lab to use a [different app](https://github.com/dockersamples/dotnet-album-viewer) now. This was done in #323/

**Comment by timomta** [comment]
Thank you Mano
