### ISSUE TITLE
URL in tutorial not available anymore

### ISSUE THREAD

**Issue by edipetres** [docker/labs#322]
** PLEASE ONLY USE THIS ISSUE TRACKER TO SUBMIT ISSUES WITH THE DOCKER LABS TUTORIAL CONTENT **

* If you have a bug working with Docker itself, not related to these labs, please file the bug on the [Docker repo](https://github.com/moby/moby) *
* If you would like general support figuring out how to do something with Docker, please use the Docker Slack channel. If you're not on that channel, sign up for the [Docker Community](http://dockr.ly/MeetUp) and you'll get an invite. *
* Or go to the [Docker Forums](https://forums.docker.com/) *

Please provide the following information so we can assess the issue you're having

**Which lab is it that you're having issues with?**
labs/developer-tools/nodejs/porting/3_publish_image.md
[Tutorial that has issues](https://github.com/docker/labs/blob/master/developer-tools/nodejs/porting/3_publish_image.md)
[Wrong link the tutorial is pointing to](https://camo.githubusercontent.com/809d1a18bfe2ba8cad9b1eadc6c15807de6248a0/68747470733a2f2f646c2e64726f70626f7875736572636f6e74656e742e636f6d2f752f323333303138372f646f636b65722f6c6162732f6e6f64652f72656769737472795f312e706e67)

**Description**

The urls found in the tutorial above hosted on dropbox are no longer available. The link goes out for image files.

**Comment by ManoMarks** [comment]
@lucj looks like all links on https://github.com/docker/labs/blob/master/developer-tools/nodejs/porting/3_publish_image.md have broken

**Comment by lucj** [comment]
@ManoMarks I changed the links and submitted a PR

**Comment by arush-sal** [comment]
@ManoMarks I guess this should be closed now.
