### ISSUE TITLE
connection: 'mongo' not connections: 'sails-mongo'

### ISSUE THREAD

**Issue by qiulang** [docker/labs#331]
** PLEASE ONLY USE THIS ISSUE TRACKER TO SUBMIT ISSUES WITH THE DOCKER LABS TUTORIAL CONTENT **

* If you have a bug working with Docker itself, not related to these labs, please file the bug on the [Docker repo](https://github.com/moby/moby) *
* If you would like general support figuring out how to do something with Docker, please use the Docker Slack channel. If you're not on that channel, sign up for the [Docker Community](http://dockr.ly/MeetUp) and you'll get an invite. *
* Or go to the [Docker Forums](https://forums.docker.com/) *

Please provide the following information so we can assess the issue you're having

**Which lab is it that you're having issues with?**

Setup our sample Node.js application

**Description**

I know nothing about sails but I found I need to set this in my config/model.js:
connection: 'mongo' , not connections: 'sails-mongo'
otherwise it would use localDiskDb

**Comment by ManoMarks** [comment]
Resolved in #394
