### ISSUE TITLE
Invalid characters in URL issue in Java CI/CD chapter on Windows

### ISSUE THREAD

**Issue by jdleesmiller** [docker/labs#366]
**Which lab is it that you're having issues with?**

https://github.com/docker/labs/blob/master/developer-tools/java/chapters/ch09-cicd.adoc

**Description**

Several participants running docker for windows and git bash encountered an issue in a recent workshop: when they try to build the `Dockerfile` with `docker-compose up -d`, the Jenkins `plugins.sh` script fails with an error from `curl` about invalid characters in a URL.

The problem seems to be that `git` checks the file out with windows newlines, which then break the `curl` command that jenkins' `plugins.sh` script builds.

Workaround: run `dos2unix plugins.txt` before `docker compose up -d`.

I think it's that git is checking the file out with native newlines, not that it's stored with windows newlines in the repo. Possibly one best solved with documentation.

**Comment by jdleesmiller** [comment]
CC @arun-gupta , as discussed.

**Comment by arun-gupta** [comment]
@fabianenardon thoughts?

**Comment by fabianenardon** [comment]
Good catch, @jdleesmiller . I checked and the file is indeed in the unix format, so it may be the case that you mentioned. Per your suggestion, I added a note suggesting to run `dos2unix` when running the lab on windows. See https://github.com/docker/labs/blob/master/developer-tools/java/chapters/ch09-cicd.adoc

**Comment by jdleesmiller** [comment]
@fabianenardon Looks good to me!

Closed with https://github.com/docker/labs/pull/367.
