### ISSUE TITLE
No REPLICAS after stack deploy

### ISSUE THREAD

**Issue by bigkrp** [docker/labs#371]
**Which lab is it that you're having issues with?**

https://github.com/docker/labs/blob/master/beginner/chapters/votingapp.md
**Description**
When i tried to verify that stack has deployed, i have no `REPLICAS` for postgres:9.4 and dockersamples/examplevotingapp_worker:latest. And as a result, the application does not work for me.

**Steps to reproduce the issue, if relevant:**
1. `git clone https://github.com/docker/example-voting-app.git`
2. `cd example-voting-app`
3. `docker swarm init`
4. `docker stack deploy --compose-file docker-stack.yml vote`
5. `docker stack services vote`
6. Open in browser localhost:5000 

**Describe the results you received:**
non-working application

**Describe the results you expected:**
working application

**Output of `docker version`:**

```
Client:
 Version:         1.13.1
 API version:     1.26
 Package version: <unknown>
 Go version:      go1.8.3
 Git commit:      b5e3294/1.13.1
 Built:           Wed Aug 16 13:58:20 2017
 OS/Arch:         linux/amd64

Server:
 Version:         1.13.1
 API version:     1.26 (minimum version 1.12)
 Package version: <unknown>
 Go version:      go1.8.3
 Git commit:      b5e3294/1.13.1
 Built:           Wed Aug 16 13:58:20 2017
 OS/Arch:         linux/amd64
 Experimental:    false
```

**Output of `docker info`:**

```
Containers: 37
 Running: 5
 Paused: 0
 Stopped: 32
Images: 22
Server Version: 1.13.1
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: journald
Cgroup Driver: systemd
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Authorization: rhel-push-plugin
Swarm: active
 NodeID: beb57ltfpevg2r2rnsorv65l7
 Is Manager: true
 ClusterID: cymy41ooalhja4ots1rb6nigl
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 192.168.3.88
 Manager Addresses:
  192.168.3.88:2377
Runtimes: oci runc
Default Runtime: oci
Init Binary: /usr/libexec/docker/docker-init-current
containerd version:  (expected: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1)
runc version: N/A (expected: 9df8b306d01f59d3a8029be411de015b7304dd8f)
init version: N/A (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 seccomp
  WARNING: You're not using the default seccomp profile
  Profile: /etc/docker/seccomp.json
 selinux
Kernel Version: 4.13.5-200.fc26.x86_64
Operating System: Fedora 26 (Workstation Edition)
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 3
CPUs: 4
Total Memory: 7.697 GiB
Name: bigkrp-bigkrpdomain
ID: J5Y2:A32J:AI4Q:F4YN:5FDF:FZZG:BKYA:2HUS:ZEXF:MELX:223M:E2ZC
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: bigkrp
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Registries: docker.io (secure), registry.fedoraproject.org (secure), registry.access.redhat.com (secure), docker.io (secure)
```

**Comment by ManoMarks** [comment]
@bigkrp you are using an old version of Docker, can you update to the latest and try again? https://www.docker.com/get-docker

**Comment by bigkrp** [comment]
I updated docker in accordance with [this guide](https://docs.docker.com/engine/installation/linux/docker-ce/fedora/#install-docker-ce-1)

and stack has deploed
![2017-11-03 14-10-59](https://user-images.githubusercontent.com/11586744/32373261-19dfff8e-c0a1-11e7-813c-345a1e2776d0.png)

But web-view didn't work, when i tried visit http://localhost:5000/

**Comment by htmyheart** [comment]
hi @bigkrp please check github: https://github.com/dockersamples/example-voting-app
I ran `docker-compose up` before deploy stack and it worked fine with me. Please try.

**Comment by ManoMarks** [comment]
@bigkrp I'm unable to reproduce, but I don't have Fedora. Can you try this lab and see if it works in play-with-docker? http://training.play-with-docker.com/swarm-stack-intro/
If so that might indicate either a problem with Fedora or a set-up issue on your computer

**Comment by ManoMarks** [comment]
If you continue to have an issue I suggest raising it on https://github.com/docker/for-linux
