### ISSUE TITLE
ping docker.com not working 

### ISSUE THREAD

**Issue by yongshin** [docker/labs#385]
Ping docker.com does not come back with a response, we suggest replacing docker.com with dockercon.com 

```
ubuntu@engine01:~$ ping docker.com
PING docker.com (34.196.107.217) 56(84) bytes of data.
--- docker.com ping statistics ---
9 packets transmitted, 0 received, 100% packet loss, time 7999ms
```

https://github.com/docker/labs/blob/master/networking/A2-bridge-networking.md

**Comment by ManoMarks** [comment]
Fixed in #386
