### ISSUE TITLE
ERROR: pull access denied for docker-hadoop-example

### ISSUE THREAD

**Issue by Abunwer** [docker/labs#390]
**Which lab is it that you're having issues with?**

https://github.com/docker/labs/blob/master/developer-tools/java/chapters/ch11-bigdata.adoc

**Description**

I have problem when I was implementing this lab step by step , the problem is when I put "docker-compose up -d" it give me this output "ERROR: pull access denied for docker-hadoop-example, repository does not exist or may require 'docker login'" 
I tried to login but the problem still exist  

**Output of `docker version`:**

```
Docker version 17.12.0-ce, build c97c6d6

```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 9
Server Version: 17.12.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 29
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.10.0-42-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 3.773GiB
Name: omar-Lenovo-E31-70
ID: DYDV:R426:HFLZ:LBJU:MZQ7:IAEZ:7W6M:2P2O:SNJM:MQJY:W4YF:4XG3
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: abunwer61
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support

```

**Comment by ManoMarks** [comment]
@arun-gupta

**Comment by arun-gupta** [comment]
@fabianenardon any idea?

**Comment by fabianenardon** [comment]
This image is created when you build the project (one step before the one you got the error). Are you sure you ran the command below before running 'docker-compose up -d'?

`cd sample` 
`mvn clean install -Papp-docker-image`

If the build was successful, you should see `docker-hadoop-example` listed when you run `docker images`.

**Comment by Abunwer** [comment]
@fabianenardon yes I did that .... I was following the lab step by step but I could't solve the problem.

**Comment by fabianenardon** [comment]
@Abunwer Can you post the output of the `mvn clean install -Papp-docker-image` command? And also check if you can see the `docker-hadoop-example` image when you run `docker images`.

**Comment by Abunwer** [comment]
Here is the output of  mvn clean install -Papp-docker-image : 
`[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building docker-hadoop-example 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ docker-hadoop-example ---
[INFO] Deleting /home/omar/hadoop-docker-demo/sample/target
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ docker-hadoop-example ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] 
[INFO] --- maven-compiler-plugin:2.5.1:compile (default-compile) @ docker-hadoop-example ---
[INFO] Compiling 1 source file to /home/omar/hadoop-docker-demo/sample/target/classes
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ docker-hadoop-example ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 4 resources
[INFO] 
[INFO] --- maven-compiler-plugin:2.5.1:testCompile (default-testCompile) @ docker-hadoop-example ---
[INFO] Compiling 2 source files to /home/omar/hadoop-docker-demo/sample/target/test-classes
[INFO] 
[INFO] --- maven-surefire-plugin:2.17:test (default-test) @ docker-hadoop-example ---
[INFO] Surefire report directory: /home/omar/hadoop-docker-demo/sample/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.examples.hadoop.AppTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.055 sec - in org.examples.hadoop.AppTest

Results :

Tests run: 1, Failures: 0, Errors: 0, Skipped: 0

[INFO] 
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ docker-hadoop-example ---
[INFO] Building jar: /home/omar/hadoop-docker-demo/sample/target/docker-hadoop-example-1.0-SNAPSHOT.jar
[INFO] 
[INFO] --- maven-assembly-plugin:2.3:single (make-mr) @ docker-hadoop-example ---
[INFO] Reading assembly descriptor: /home/omar/hadoop-docker-demo/sample/src/main/resources/assembly/hadoop-mr.xml
[INFO] Building jar: /home/omar/hadoop-docker-demo/sample/target/docker-hadoop-example-1.0-SNAPSHOT-mr.jar
[INFO] 
[INFO] --- docker-maven-plugin:0.20.0:build (docker-build) @ docker-hadoop-example ---
[WARNING] The assembly descriptor contains a filesystem-root relative reference, which is not cross platform compatible /jar
[WARNING] The assembly descriptor contains a filesystem-root relative reference, which is not cross platform compatible /test-data
[INFO] Copying files to /home/omar/hadoop-docker-demo/sample/target/docker/docker-hadoop-example/build/maven
[INFO] Building tar: /home/omar/hadoop-docker-demo/sample/target/docker/docker-hadoop-example/tmp/docker-build.tar
[INFO] DOCKER> docker-build.tar: Created [docker-hadoop-example] in 1 second 
723254a2c089: Pull complete 
abe15a44e12f: Pull complete 
409a28e3cc3d: Pull complete 
503166935590: Pull complete 
043a12c29ea4: Pull complete 
303620452447: Pull complete 
c61f95baa024: Pull complete 
3f2018472a1f: Pull complete 
a25f8a69c882: Pull complete 
ff67c8538c47: Pull complete 
8c348b894f56: Pull complete 
7636ce7c4d56: Pull complete 
[INFO] DOCKER> Digest: sha256:b1b158290fae4642699f9472ecd04b5487e9f7bee53b229d5b6b560af65ddd27							
[INFO] DOCKER> Status: Downloaded newer image for maven:latest
[INFO] DOCKER> Pulled maven:latest in 25 minutes and 33 seconds 
[WARNING] The assembly descriptor contains a filesystem-root relative reference, which is not cross platform compatible /m2
[INFO] Copying files to /home/omar/hadoop-docker-demo/sample/target/docker/docker-hadoop-example-tests/build/maven
[INFO] Building tar: /home/omar/hadoop-docker-demo/sample/target/docker/docker-hadoop-example-tests/tmp/docker-build.tar
[INFO] DOCKER> docker-build.tar: Created [docker-hadoop-example-tests] in 279 milliseconds
[INFO] DOCKER> [docker-hadoop-example-tests]: Built image sha256:e2e74
[INFO] 
[INFO] --- maven-install-plugin:2.5.2:install (default-install) @ docker-hadoop-example ---
[INFO] Installing /home/omar/hadoop-docker-demo/sample/target/docker-hadoop-example-1.0-SNAPSHOT.jar to /home/omar/.m2/repository/org/examples/hadoop/docker-hadoop-example/1.0-SNAPSHOT/docker-hadoop-example-1.0-SNAPSHOT.jar
[INFO] Installing /home/omar/hadoop-docker-demo/sample/pom.xml to /home/omar/.m2/repository/org/examples/hadoop/docker-hadoop-example/1.0-SNAPSHOT/docker-hadoop-example-1.0-SNAPSHOT.pom
[INFO] Installing /home/omar/hadoop-docker-demo/sample/target/docker-hadoop-example-1.0-SNAPSHOT-mr.jar to /home/omar/.m2/repository/org/examples/hadoop/docker-hadoop-example/1.0-SNAPSHOT/docker-hadoop-example-1.0-SNAPSHOT-mr.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 26:35 min
[INFO] Finished at: 2018-01-09T19:54:24+01:00
[INFO] Final Memory: 40M/324M
[INFO] ------------------------------------------------------------------------
`

and this output of docker images: 
`REPOSITORY                    TAG                 IMAGE ID            CREATED             SIZE
docker-hadoop-example-tests   latest              e2e74c0ec658        8 minutes ago       748MB
docker-hadoop-example         latest              30c9bfd7ff85        33 minutes ago      1.2GB
`

**Comment by fabianenardon** [comment]
Your `docker images` output shows that `docker-hadoop-example:latest` is available, so `docker-compose up` should find it. Can you run the docker-compose step again and check if you get the same error?

**Comment by Abunwer** [comment]
I'm sorry I have bad Internet connection .... this is the output of docker-compose up -d : 
Starting mongo ... 
namenode is up-to-date
docker_datanode_1 is up-to-date
secondarynamenode is up-to-date
yarn is up-to-date
Starting mongo ... error

ERROR: for mongo  Cannot start service mongo: driver failed programming external connectivity on endpoint mongo (64c7c9d3769710ef2f27d96686fffe29d2ec99e9d07778b2ab699e3cc2e4da29): Error starting userland proxy: listen tcp 0.0.0.0:27017: bind: address already in use

ERROR: for mongo  Cannot start service mongo: driver failed programming external connectivity on endpoint mongo (64c7c9d3769710ef2f27d96686fffe29d2ec99e9d07778b2ab699e3cc2e4da29): Error starting userland proxy: listen tcp 0.0.0.0:27017: bind: address already in use
ERROR: Encountered errors while bringing up the project.

**Comment by fabianenardon** [comment]
Run `docker-compose down` first to make sure the containers are not running. The `address already in use` error means you have services running already. Then, run `docker-compose up -d` again.

**Comment by Abunwer** [comment]
output of docker-compose down : 

Stopping docker_nodemanager_1 ... done
Stopping yarn                 ... done
Stopping secondarynamenode    ... done
Stopping docker_datanode_1    ... done
Stopping namenode             ... done
Removing docker_nodemanager_1 ... done
Removing yarn                 ... done
Removing secondarynamenode    ... done
Removing docker_datanode_1    ... done
Removing namenode             ... done
Removing mongo                ... done
Removing network docker_default

but the output of docker-compose up -d : 

Starting mongo ... 
namenode is up-to-date
docker_datanode_1 is up-to-date
secondarynamenode is up-to-date
yarn is up-to-date
Starting mongo ... error

ERROR: for mongo  Cannot start service mongo: driver failed programming external connectivity on endpoint mongo (4b5b9ee2e580228e8d15bf4b2209fdf246720aee07592f9a03da55c80fdea725): Error starting userland proxy: listen tcp 0.0.0.0:27017: bind: address already in use

ERROR: for mongo  Cannot start service mongo: driver failed programming external connectivity on endpoint mongo (4b5b9ee2e580228e8d15bf4b2209fdf246720aee07592f9a03da55c80fdea725): Error starting userland proxy: listen tcp 0.0.0.0:27017: bind: address already in use
ERROR: Encountered errors while bringing up the project.

**Comment by fabianenardon** [comment]
Please, make sure there is nothing running on port 27017.

**Comment by Abunwer** [comment]
@fabianenardon Thank you very much .... it's work now :+1: 
I found that the port number 27017 in use I killed the process by enter "sudo kill $(sudo lsof -t -i:27017)"
and then start to work fine! :smile:
