### ISSUE TITLE
12 factor lab missing step to create message API for Sails app

### ISSUE THREAD

**Issue by mdorn** [docker/labs#393]
**Which lab is it that you're having issues with?**

12factor

**Description**

In step `00`, a new app `messageApp` is created, but it's missing instructions to create the `message` API.  There should be a line after creating the app that instructs the user to do:

    sails generate api message

**Comment by ManoMarks** [comment]
@lucj

**Comment by lucj** [comment]
I've just tested it, thanks for the fix.
