### ISSUE TITLE
standard_init_linux.go:185: exec user process caused "no such file or directory"

### ISSUE THREAD

**Issue by Jacksonary** [docker/labs#395]
I have some troubles with docker-compose when I try this example https://github.com/docker/labs/blob/master/developer-tools/java-debugging/IntelliJ-README.md . There is many same warning like this "webserver_1  | standard_init_linux.go:185: exec user process caused "no such file or directory"",I had tried my best to deal with it like " git config --global core.autocrlf false" then git clone agin, but I don't success, change  "#!/bin/bash" in "labs\developer-tools\java-debugging\registration-webserver\tomcat\run.sh"  to "#!/bin/sh", but it can't work, I need your help!

**Comment by ManoMarks** [comment]
Hi @Jacksonary. Can you provide the following information?

Also related you may find answers here:
https://stackoverflow.com/questions/46651861/docker-error-standard-init-linux-go185-exec-user-process-caused-no-such-file

Please provide the following information so we can assess the issue you're having

**Which lab is it that you're having issues with?**


**Description**



**Steps to reproduce the issue, if relevant:**
1.
2.
3.

**Describe the results you received:**


**Describe the results you expected:**


**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, Docker for Mac, Docker for Windows, VirtualBox, physical, etc.):**

**Comment by Jacksonary** [comment]
Thanks, @ManoMarks ,I had tried like that method, but It does not work. However, I find it working successfully when I do like sample today, but I do nothing. Any way,  I have do it successfully,but when I To go to the application, Click on /UserSignup link, it can not find page of UserSignup.
`webserver_1  | Jan 07, 2018 5:50:24 AM org.apache.catalina.startup.TldConfig execute
webserver_1  | INFO: At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
webserver_1  | SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
webserver_1  | SLF4J: Defaulting to no-operation (NOP) logger implementation
webserver_1  | SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
webserver_1  | Jan 07, 2018 5:50:24 AM org.apache.catalina.core.StandardContext startInternal
webserver_1  | SEVERE: One or more listeners failed to start. Full details will be found in the appropriate container log file
webserver_1  | Jan 07, 2018 5:50:24 AM org.apache.catalina.core.StandardContext startInternal
webserver_1  | SEVERE: Context [/UserSignup] startup failed due to previous errors`

**Comment by ManoMarks** [comment]
@Jacksonary please provide the other information I requested above

**Comment by Jacksonary** [comment]
@ManoMarks ,

Which lab is it that you're having issues with?
https://github.com/docker/labs/blob/master/developer-tools/java-debugging/IntelliJ-README.md

Description：Just as I described above;

Describe the results you received: I can not open the link of `/UserSignup`(404); and PowerShell output is as follows：
`webserver_1 | Jan 07, 2018 5:50:24 AM org.apache.catalina.startup.TldConfig execute webserver_1 | INFO: At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time. webserver_1 | SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder". webserver_1 | SLF4J: Defaulting to no-operation (NOP) logger implementation webserver_1 | SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details. webserver_1 | Jan 07, 2018 5:50:24 AM org.apache.catalina.core.StandardContext startInternal webserver_1 | SEVERE: One or more listeners failed to start. Full details will be found in the appropriate container log file webserver_1 | Jan 07, 2018 5:50:24 AM org.apache.catalina.core.StandardContext startInternal webserver_1 | SEVERE: Context [/UserSignup] startup failed due to previous errors`

Describe the results you expected: I want open the link of `/UserSignup` in the Tomcat Web Application Manager page;

Output of docker version:` Docker version 17.09.1-ce, build 19e2cf6`

Output of docker info:
```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 62
Server Version: 17.09.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.49-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.934GiB
Name: moby
ID: PRCF:DKQG:V34V:IS6T:7DVB:QJXG:H6N5:XNIW:GPZH:77M4:E4KP:V5BR
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 16
 Goroutines: 26
 System Time: 2018-01-08T01:32:28.4868995Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Registry Mirrors:
 https://uv6ibf1b.mirror.aliyuncs.com/
Live Restore Enabled: false
```

Additional environment details (AWS, Docker for Mac, Docker for Windows, VirtualBox, physical, etc.):Docker for Windows

**Comment by ManoMarks** [comment]
And are you using Docker for Mac, or Docker for Windows?

**Comment by Jacksonary** [comment]
@ManoMarks ,
Yes, As I said above，I am using Docker for Windows

**Comment by spara** [comment]
@Jacksonary Can you copy and paste the logs of the appserver? e.g. docker logs <container>

**Comment by Jacksonary** [comment]
@spara ，I've pasted the above information into the problem description section
