### ISSUE TITLE
When running vim any terminal, escape key is not bound to the terminal.

### ISSUE THREAD

**Issue by sstern6** [docker/labs#409]
** PLEASE ONLY USE THIS ISSUE TRACKER TO SUBMIT ISSUES WITH THE DOCKER LABS TUTORIAL CONTENT **

* If you have a bug working with Docker itself, not related to these labs, please file the bug on the [Docker repo](https://github.com/moby/moby) *
* If you would like general support figuring out how to do something with Docker, please use the Docker Slack channel. If you're not on that channel, sign up for the [Docker Community](http://dockr.ly/MeetUp) and you'll get an invite. *
* Or go to the [Docker Forums](https://forums.docker.com/) *

Please provide the following information so we can assess the issue you're having

**Which lab is it that you're having issues with?**
Docker For Developers

**Description**
https://training.play-with-docker.com/ops-s1-images/

When editing the index.js file in the `Image creation using a Dockerfile`, when you are trying to save, the `<esc>` key is not bound to the terminal and does not allow you to save or quit.
**Steps to reproduce the issue, if relevant:**
1. touch index.js
2. vi index.js
3. add content
4. <esc> to save does not work

**Comment by ManoMarks** [comment]
Please file this issue on this repository: https://github.com/play-with-docker/play-with-kubernetes.github.io
