### ISSUE TITLE
Unable to pull windows image

### ISSUE THREAD

**Issue by mukulmeister** [docker/labs#465]
I have windows 10 Ent (10.0.17134) X64 version , while trying to pull windows image : mcr.microsoft.com/windows/nanoserver:1809 i am getting error no matching manifest for unknown in the manifest list entries.

**Comment by StefanScherer** [comment]
On Windows you can run windows containers that have the same or older version of your kernel.
See the Windows container version compatibility page at https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/version-compatibility

In your case it's Windows 10 1803, so you can use mcr.microsoft.com/windows/nanoserver:1803 instead.

**Comment by mukulmeister** [comment]
Thanks for replying @StefanScherer , i figured that out and now it works.
