### ISSUE TITLE
No replicas running in Docker for beginner chapter 3

### ISSUE THREAD

**Issue by TQuy** [docker/labs#525]
when I run `docker swarn init`, there is a notification
> Error response from daemon: could not choose an IP address to advertise since this system has multiple addresses on interface wlp2s0 (2405:4803:c743:3030:decd:35a2:df24:9c2 and 2405:4803:c743:3030:1a5b:64c3:78a0:f42d) - specify one with --advertise-addr

Then I run `docker swarm init --advertise-addr 2405:4803:c743:3030:decd:35a2:df24:9c2`. Next, I continue follow the tutorial till the step `docker stack services vote` but there is no replicas running
![image](https://user-images.githubusercontent.com/45731304/116332071-3bfd0680-a7fb-11eb-81ed-8eb0c368056a.png)

**Comment by wlbwlbwlb** [comment]
did you solve this problem?

**Comment by TQuy** [comment]
> did you solve this problem?  

I didn't
