### ISSUE TITLE
Docker service ls command should show state of each tasks. 

### ISSUE THREAD

**Issue by yeshavora** [docker/labs#65]
The docker service command should be fixed to show the state of tasks properly. 
It is hard to figure out the state of a task. It becomes hard to debug failure scenarios too. 

$ docker service ls
ID            NAME         REPLICAS  IMAGE                    COMMAND
acemxpti7m36  wildfly-app  0/2       arungupta/wildfly-app:1

**Comment by hairyhenderson** [comment]
@yeshavora - I think a more appropriate place to log this would be in [docker/docker](https://github.com/docker/docker)

**Comment by ManoMarks** [comment]
Agreed, please submit an issue on docker/docker
