### ISSUE TITLE
.net on windows - docker-machine windows

### ISSUE THREAD

**Issue by fthamura** [docker/labs#69]
is it possible we can have also lab related to windows (2016)

docker image on docker-windows
docker-machine to windows server?

ass additional to 
https://github.com/docker/labs/blob/master/windows/readme.md

**Comment by ManoMarks** [comment]
Definitely planned!

**Comment by fthamura** [comment]
We have.win2016 server, still.findout how to connect to docker machine

Any glue?

**Comment by ManoMarks** [comment]
Update on this, we don't yet have a way to provision Windows hosts in Docker Machine. So this will have to wait until this is possible.
