### ISSUE TITLE
Add Installing Docker on WS2016 using DSC to Labs

### ISSUE THREAD

**Issue by PlagueHO** [docker/labs#80]
As per suggestion from @ManoMarks , I would like to add a tutorial showing how to install Docker on Windows Server 2016 (Server or Server Core) using PowerShell DSC.

This is performed using [a script on PowerShell Gallery](https://www.powershellgallery.com/packages/Install-DockerOnWS2016UsingDSC).

The commands to execute are:
```powershell
Install-Script -Name Install-DockerOnWS2016UsingDSC
Install-DockerOnWS2016UsingDSC.ps1
```

**Comment by ManoMarks** [comment]
#82
