### ISSUE TITLE
Service 'web' failed to build: unknown blob=============> ]

### ISSUE THREAD

**Issue by eliassal** [docker/labs#96]
HI,
I am trying to build this lab but getting the error 
1B[31mERROR[0m: Service 'web' failed to build: unknown blob=============> ]
I am running on win10 enterprise, Hyper-V enbaled, docker for windows beta but I did not install windows containers.
Of course, I have changed the external name of the network in the docker.compose.windows to the name of the nat in my hyper-V.
So does this tutorial needs windows containers?
2nd, looking at your instructions on how to install containers in win 10, it is indicated to add the docker to the path after downloading, wouldn²t this disturb the command already mapped by Docker for windows?
Thanks

**Comment by ManoMarks** [comment]
Hi @eliassal,

Which lab are you trying to run?

**Comment by eliassal** [comment]
Multi-Container Applicationns at
https://github.com/docker/labs/blob/master/windows/windows-containers/MultiContainerApp.md

**Comment by ManoMarks** [comment]
Yes that lab does require the use of Windows containers, so you need to switch to Windows containers. That won't require an install if you're up to date on all updates to Windows 10. You also don't need to add anything to the path.

**Comment by ManoMarks** [comment]
The error you are getting is because you didn't switch to windows containers
![gif of switching to windows containers](https://github.com/docker/labs/blob/master/windows/windows-containers/images/docker-for-windows-switch.gif)

**Comment by eliassal** [comment]
Ok Mano, I switched to win containers, issued the build command, getting thisthis output 

> PS E:\Project\MusicStore-master> docker-compose -f .\docker-compose.windows.yml build
> db uses an image, skipping
> Building web
> Step 1/13 : FROM microsoft/dotnet:1.0.0-preview2-windowsservercore-sdk
> 1.0.0-preview2-windowsservercore-sdk: Pulling from microsoft/dotnet
> 9c7f9c7d9bc2: Pull complete
> bc1fd41b1aa4: Pull complete
> 72be500ae6da: Pull complete
> ece219324a62: Pull complete
> 1e9785c36e6a: Pull complete
> f06a698b860b: Pull complete
> 340caf8b1001: Pull complete
> Digest: sha256:0e1e82755d2ebe26f1fc0a60fd6ea1b758b45b89d8eb3bd78991baedeac4b514
> Status: Downloaded newer image for microsoft/dotnet:1.0.0-preview2-windowsservercore-sdk
>  ---> 4154a4c864b6
> Step 2/13 : SHELL powershell -Command $ErrorActionPreference = 'Stop';
>  ---> Running in c349873ed98b
>  ---> 92e1a7cc8d48
> Removing intermediate container c349873ed98b
> Step 3/13 : RUN set-itemproperty -path 'HKLM:\SYSTEM\CurrentControlSet\Services\Dnscache\Parameters' -Name ServerPriorit
> yTimeLimit -Value 0 -Type DWord
>  ---> Running in 9ffe00b297cc
> ERROR: Service 'web' failed to build: container 9ffe00b297cc8c60b4ff1d9720c02921b0fe78aa6ee32f0b07054b9544659068 encount
> ered an error during Start: failure in a Windows system call: The operation timed out because a response was not receive
> d from the Virtual Machine hosting the Container. (0xc0370109)

I even tried from a another laptop, getting the exact same error

**Comment by eliassal** [comment]
Sorry, the 2nd laptop gives a different error as follows

```
Step 1/13 : FROM microsoft/dotnet:1.0.0-preview2-windowsservercore-sdk
...............
....
...
Step 6/13 : ADD samples/MusicStore.Standalone/project.json samples/MusicStore.Standalone/project.json
 ---> Using cache
 ---> 65ae50f6fb5d
Step 7/13 : ADD NuGet.config .
 ---> Using cache
 ---> c84046b134dd
Step 8/13 : RUN dotnet restore --no-cache .\samples\MusicStore.Standalone
 ---> Running in 47c4a247e602
log  : Restoring packages for C:\MusicStore\samples\MusicStore.Standalone\project.json...
error: Unable to load the service index for source https://dotnet.myget.org/F/aspnetcore-ci-dev/api/v3/index.json.
error:   An error occurred while sending the request.
error:   The server name or address could not be resolved
ERROR: Service 'web' failed to build: The command 'powershell -Command $ErrorActionPreference = 'Stop'; dotnet restore --no-cache .\samples\MusicStore.Standalone' returned a non-zero
```

**Comment by eliassal** [comment]
Mano, while the error is persi persisting on the physical win 10 laptop which has containers enabled which is 
error:   The server name or address could not be resolved

The operations succeeded after 5 retries on THE WIN VM with Docker for windows installed and switched to Windows dows Containers.
I should admit that it is a very involved process and took a lot of time for each step.

After issuing the 
`docker-compose -f .\docker-compose.windows.yml build`
for the 5th time, I got rid on the comm error on step 8/13 and reached 

> Successfully built 799de69bb202

Then I issued 
docker-compose -f .\docker-compose.windows.yml up

started to get the following

```
Pulling db (microsoft/mssql-server-2016-express-windows:latest)...
latest: Pulling from microsoft/mssql-server-2016-express-windows
9c7f9c7d9bc2: Already exists
a668155b2edd: Pull complete
d89b36696f4d: Pull complete
4810d30c603d: Pull complete
f2b8cca22ada: Pull complete
35f6d8a76ceb: Pull complete
285c50e9b90d: Pull complete
efc96f8c3401: Pull complete
ba0f226ef4d6: Pull complete
27c44fc2dd7e: Pull complete
Digest: sha256:347a81dbbe19bf2ee5fcd3ba521a947bbffe9af8bdcbe4f3521aecfb305cc9bc
Status: Downloaded newer image for microsoft/mssql-server-2016-express-windows:latest
Creating musicstoremaster_db_1

ERROR: for db  HTTPConnectionPool(host='127.0.0.1', port=2375): Read timed out. (read timeout=60)
ERROR: An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a hig
her value (current value: 60).


```
again so many tries and setting COMPOSE_HTTP_TIMEOUT = 180, the up process went through and I was able to browse the store website from another machine using http://hostIP:5000 but not from the host itself (not able to understand why as firwall is disabled on the host win 10 running windows container).

I appreciate your efforts and help but I think all this should be optimized and get more robust. I work with docker on Linux since almost 1, spinning a new container never crossed 15 to 20 minutes whereas for running this lab it took me more that 8 hours and used 2 different hosts. Just before clicking on the post button, I retried 
docker-compose -f .\docker-compose.windows.yml build
on the win10 physical laptop
no way, exact same error after 5 minutes of wait

**Comment by eliassal** [comment]
Also, a huge surprise, I have just checked the directory
C:\ProgramData\Docker\windowsfilter
on the win10 VM, it is 24 GIG !!!!! with a lot of Guid based names directories
35f34a62175c8213b981d84964e5392d338d9f72b16b74088902183479b4ef72
73cff097674dc109928640c97811907b9680edd6401d217e53069f96c1912f62
....
........
how this can be cleaned? and why so many directories for 1 single container?
Thanks for your help

**Comment by ManoMarks** [comment]
@eliassal I'm not able to replicate your problem. Could you [submit feedback](https://docs.docker.com/docker-for-windows/#/diagnose-and-feedback) on Docker for Windows so the team can help you debug the issue?

And yes, the Windows container images are huge. That's a known issue that I believe Microsoft is working on. Using NanoServer helps but they are still large compared to Linux.

**Comment by eliassal** [comment]
OK Mano I will do, but what about the error I am getting on the physical laptop , step 8/13
```
...Step 8/13 : RUN dotnet restore --no-cache .\samples\MusicStore.Standalone
 ---> Running in 47c4a247e602
log  : Restoring packages for C:\MusicStore\samples\MusicStore.Standalone\project.json...
error: Unable to load the service index for source https://dotnet.myget.org/F/aspnetcore-ci-dev/api/v3/index.json.
error:   An error occurred while sending the request.
error:   The server name or address could not be resolved


```This is Windows container and not Docker for windows

**Comment by ManoMarks** [comment]
Docker for Windows is still the engine so report it there. We work with MS so if there's something one their end we can work it out
