### ISSUE TITLE
Service 'web' failed to build: failed to register layer: re-exec error: exit status 1

### ISSUE THREAD

**Issue by eliassal** [docker/labs#97]
Hi Mano, I tried to play today with this lab, as soon as I issue the command
`Docker-compose -f .\docker-compose.yml build
`
I get

```
Building web
Step 1/8 : FROM node:5.11.0-slim
5.11.0-slim: Pulling from library/node
8b87079b7a06: Extracting [==================================================>] 51.36 MB/51.36 MB
a3ed95caeb02: Download complete
1bb8eaf3d643: Download complete
5674f5dccbc4: Download complete
96a79bcf8a3b: Download complete
ERROR: Service 'web' failed to build: failed to register layer: re-exec error: exit status 1: output: Failed to OpenForBackup failed in Win32: open \\?\E:\Hyper-V\DockerMachines\wind
owsfilter\1d1c566d88490bc2e99798d8df8afe25328ee53c986f26731f6bf1a136d29055\usr\share\man\man3\Locale::gettext.3pm.gz: The filename, directory name, or volume label syntax is incorrec
t. (0x1f) \\?\E:\Hyper-V\DockerMachines\windowsfilter\1d1c566d88490bc2e99798d8df8afe25328ee53c986f26731f6bf1a136d29055\usr\share\man\man3\Locale::gettext.3pm.gz

```
This is on a physical win 10 machine windows containers enabled and HYper-V on
Thanks for your help

**Comment by eliassal** [comment]
Mano, just tried on the 2nd win10 VM with docker for windows, getting the exact same error

**Comment by ManoMarks** [comment]
Hmmm, works for me:

```
PS C:\Users\Mano\code\labs\developer-tools\nodejs-debugging\app> docker-compose -f .\dock
er-compose.yml build
Building web
Step 1 : FROM node:5.11.0-slim
 ---> cb888ea932ad
Step 2 : WORKDIR /code
 ---> Using cache
 ---> 3baae518ec91
Step 3 : RUN npm install -g nodemon
 ---> Using cache
 ---> db82e0d47fba
Step 4 : COPY package.json /code/package.json
 ---> Using cache
 ---> 3a9442019adf
Step 5 : RUN npm install && npm ls
 ---> Using cache
 ---> 6d56758125d8
Step 6 : RUN mv /code/node_modules /node_modules
 ---> Using cache
 ---> 00fa75230467
Step 7 : COPY . /code
 ---> Using cache
 ---> 7c2a8c98fc49
Step 8 : CMD npm start
 ---> Using cache
 ---> d23cc4cf7963
Successfully built d23cc4cf7963
```

**Comment by ManoMarks** [comment]
What's the output of docker version?

**Comment by eliassal** [comment]
I got this same output and containeres wer up and running once I switched to Linux cntainers on the win10 VM., ON both machines when I use windows containers, it does not go through. Do you use windows or linux containers?

**Comment by eliassal** [comment]
The output for docker version on the physical win 10 is
Client:
 Version:      1.13.0-dev
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   96efb2c
 Built:        Mon Oct 24 15:30:23 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.13.0-dev
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   96efb2c
 Built:        Mon Oct 24 15:30:23 2016
 OS/Arch:      windows/amd64

On the win 10 VM it is (docker for windows version)

Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Thu Oct 27 00:09:21 2016
 OS/Arch:      windows/amd64
 Experimental: true

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Thu Oct 27 00:09:21 2016
 OS/Arch:      linux/amd64
 Experimental: true

**Comment by eliassal** [comment]
Mano, also on a 3rd machine where I have Kitematic, it is working fine but as kitematic works with default linux machine and Virtualbox driver, I am not able to use the VSC. I posted several times in docker forums how start a machine  with a network adapter different from "Host-only adapter" got no response. Any idea? the thread is 
https://forums.docker.com/t/change-default-networking-from-host-only-network-to-bridged-with-vb-provider/23849

**Comment by ManoMarks** [comment]
@eliassal that node.js lab requires use of linux containers so yes it will not work when you are in Windows Container mode. So that is correct behavior.

Kitematic can be installed from Docker for Windows and should work with any of these projects but it hasn't been tested and is still a beta project.

**Comment by mwaqasraza** [comment]
On Windows 10, I am too getting this error on pulling bodgeit.


I run this command:

 docker pull psiinon/bodgeit

failed to register layer: re-exec error: exit status 1: output: Failed to OpenForBackup failed in Win32: open \\?\C:\ProgramData\Docker\windowsfilter\ad4a6b5ab514fd94b3717ead2ca07db4f57ba412aa779bf775476f3809cc7a7b\usr\share\man\man3\Locale::gettext.3pm.gz: The filename, directory name, or volume label syntax is incorrect. (0x1f) \\?\C:\ProgramData\Docker\windowsfilter\ad4a6b5ab514fd94b3717ead2ca07db4f57ba412aa779bf775476f3809cc7a7b\usr\share\man\man3\Locale::gettext.3pm.gz

**Comment by ToeToeAung** [comment]
I am also getting the same error as above. Is there any reply on this?

**Comment by ManoMarks** [comment]
Please take me off email cc on this, I'm no longer at Docker and have
explicitly unsubscribed
