### ISSUE TITLE
VS 2K15 instead of VSC

### ISSUE THREAD

**Issue by eliassal** [docker/labs#98]
Hi, is it possible to use VS 2K15 instead of VSC? as this tutorial is not going through on windows containers, I decided to run it with my  Kitematic setup on a win10 physical desktop.

Docker-compse worked fine and I was able to access the website at http://192.168.99.100:8000/ .

What is needed for VS to make it possible following this tutorial?
Thanks

**Comment by ManoMarks** [comment]
We should have a separate VS 2K15 tutorial not a replacement for VSC.

**Comment by spara** [comment]
The VS2015 debugger does not associate node.js code running in Docker with the code in the shared directory, preventing debugging. This was registered as an issue with and earlier version of nodejstools without a resolution (https://github.com/Microsoft/nodejstools/issues/224)

Have filed issue on nodejstools: [Debugger: No code has been loaded for this code location #1421](https://github.com/docker/labs/tree/master/developer-tools/nodejs-debugging)
